// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package busbar

import (
	"context"
	"reflect"

	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInfo(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInfoResult
	err := ctx.Invoke("busbar:index/getInfo:getInfo", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getInfo.
type GetInfoResult struct {
	AuthModules       []string `pulumi:"authModules"`
	ConfigPersistence bool     `pulumi:"configPersistence"`
	ConfigVersion     int      `pulumi:"configVersion"`
	HookPlugins       []string `pulumi:"hookPlugins"`
	// The provider-assigned unique ID for this managed resource.
	Id            string `pulumi:"id"`
	Models        int    `pulumi:"models"`
	Pools         int    `pulumi:"pools"`
	Providers     int    `pulumi:"providers"`
	StartedAt     int    `pulumi:"startedAt"`
	UptimeSeconds int    `pulumi:"uptimeSeconds"`
	Version       string `pulumi:"version"`
	WeightedFloor bool   `pulumi:"weightedFloor"`
}

func GetInfoOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetInfoResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetInfoResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("busbar:index/getInfo:getInfo", nil, GetInfoResultOutput{}, options).(GetInfoResultOutput), nil
	}).(GetInfoResultOutput)
}

// A collection of values returned by getInfo.
type GetInfoResultOutput struct{ *pulumi.OutputState }

func (GetInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInfoResult)(nil)).Elem()
}

func (o GetInfoResultOutput) ToGetInfoResultOutput() GetInfoResultOutput {
	return o
}

func (o GetInfoResultOutput) ToGetInfoResultOutputWithContext(ctx context.Context) GetInfoResultOutput {
	return o
}

func (o GetInfoResultOutput) AuthModules() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInfoResult) []string { return v.AuthModules }).(pulumi.StringArrayOutput)
}

func (o GetInfoResultOutput) ConfigPersistence() pulumi.BoolOutput {
	return o.ApplyT(func(v GetInfoResult) bool { return v.ConfigPersistence }).(pulumi.BoolOutput)
}

func (o GetInfoResultOutput) ConfigVersion() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.ConfigVersion }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) HookPlugins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInfoResult) []string { return v.HookPlugins }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) Models() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.Models }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) Pools() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.Pools }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) Providers() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.Providers }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) StartedAt() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.StartedAt }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) UptimeSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v GetInfoResult) int { return v.UptimeSeconds }).(pulumi.IntOutput)
}

func (o GetInfoResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetInfoResult) string { return v.Version }).(pulumi.StringOutput)
}

func (o GetInfoResultOutput) WeightedFloor() pulumi.BoolOutput {
	return o.ApplyT(func(v GetInfoResult) bool { return v.WeightedFloor }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInfoResultOutput{})
}
