// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package busbar

import (
	"context"
	"reflect"

	"errors"
	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Hook struct {
	pulumi.CustomResourceState

	// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
	At pulumi.StringPtrOutput `pulumi:"at"`
	// Whether this hook is the default for its stage. Write-only (not echoed by reads).
	Default pulumi.BoolPtrOutput `pulumi:"default"`
	// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
	Global pulumi.BoolOutput `pulumi:"global"`
	// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
	Name pulumi.StringOutput `pulumi:"name"`
	// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
	OnEmpty pulumi.StringPtrOutput `pulumi:"onEmpty"`
	// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
	OnError pulumi.StringOutput `pulumi:"onError"`
	// Ordering priority within a stage. Defaults to 0.
	Priority pulumi.IntOutput `pulumi:"priority"`
	// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
	Prompt pulumi.StringOutput `pulumi:"prompt"`
	// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
	Settings pulumi.StringOutput `pulumi:"settings"`
	// Unix socket path to the hook process. Exactly one of socket or webhook.
	Socket pulumi.StringPtrOutput `pulumi:"socket"`
	// Per-call timeout in milliseconds. Defaults to 1.
	TimeoutMs pulumi.IntOutput `pulumi:"timeoutMs"`
	// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
	User pulumi.StringOutput `pulumi:"user"`
	// Webhook URL for the hook. Exactly one of socket or webhook.
	Webhook pulumi.StringPtrOutput `pulumi:"webhook"`
}

// NewHook registers a new resource with the given unique name, arguments, and options.
func NewHook(ctx *pulumi.Context,
	name string, args *HookArgs, opts ...pulumi.ResourceOption) (*Hook, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Kind == nil {
		return nil, errors.New("invalid value for required argument 'Kind'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Hook
	err := ctx.RegisterResource("busbar:index/hook:Hook", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHook gets an existing Hook resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHook(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HookState, opts ...pulumi.ResourceOption) (*Hook, error) {
	var resource Hook
	err := ctx.ReadResource("busbar:index/hook:Hook", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Hook resources.
type hookState struct {
	// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
	At *string `pulumi:"at"`
	// Whether this hook is the default for its stage. Write-only (not echoed by reads).
	Default *bool `pulumi:"default"`
	// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
	Global *bool `pulumi:"global"`
	// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
	Kind *string `pulumi:"kind"`
	// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
	Name *string `pulumi:"name"`
	// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
	OnEmpty *string `pulumi:"onEmpty"`
	// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
	OnError *string `pulumi:"onError"`
	// Ordering priority within a stage. Defaults to 0.
	Priority *int `pulumi:"priority"`
	// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
	Prompt *string `pulumi:"prompt"`
	// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
	Settings *string `pulumi:"settings"`
	// Unix socket path to the hook process. Exactly one of socket or webhook.
	Socket *string `pulumi:"socket"`
	// Per-call timeout in milliseconds. Defaults to 1.
	TimeoutMs *int `pulumi:"timeoutMs"`
	// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
	User *string `pulumi:"user"`
	// Webhook URL for the hook. Exactly one of socket or webhook.
	Webhook *string `pulumi:"webhook"`
}

type HookState struct {
	// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
	At pulumi.StringPtrInput
	// Whether this hook is the default for its stage. Write-only (not echoed by reads).
	Default pulumi.BoolPtrInput
	// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
	Global pulumi.BoolPtrInput
	// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
	Kind pulumi.StringPtrInput
	// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
	Name pulumi.StringPtrInput
	// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
	OnEmpty pulumi.StringPtrInput
	// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
	OnError pulumi.StringPtrInput
	// Ordering priority within a stage. Defaults to 0.
	Priority pulumi.IntPtrInput
	// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
	Prompt pulumi.StringPtrInput
	// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
	Settings pulumi.StringPtrInput
	// Unix socket path to the hook process. Exactly one of socket or webhook.
	Socket pulumi.StringPtrInput
	// Per-call timeout in milliseconds. Defaults to 1.
	TimeoutMs pulumi.IntPtrInput
	// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
	User pulumi.StringPtrInput
	// Webhook URL for the hook. Exactly one of socket or webhook.
	Webhook pulumi.StringPtrInput
}

func (HookState) ElementType() reflect.Type {
	return reflect.TypeOf((*hookState)(nil)).Elem()
}

type hookArgs struct {
	// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
	At *string `pulumi:"at"`
	// Whether this hook is the default for its stage. Write-only (not echoed by reads).
	Default *bool `pulumi:"default"`
	// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
	Global *bool `pulumi:"global"`
	// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
	Kind string `pulumi:"kind"`
	// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
	Name *string `pulumi:"name"`
	// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
	OnEmpty *string `pulumi:"onEmpty"`
	// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
	OnError *string `pulumi:"onError"`
	// Ordering priority within a stage. Defaults to 0.
	Priority *int `pulumi:"priority"`
	// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
	Prompt *string `pulumi:"prompt"`
	// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
	Settings *string `pulumi:"settings"`
	// Unix socket path to the hook process. Exactly one of socket or webhook.
	Socket *string `pulumi:"socket"`
	// Per-call timeout in milliseconds. Defaults to 1.
	TimeoutMs *int `pulumi:"timeoutMs"`
	// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
	User *string `pulumi:"user"`
	// Webhook URL for the hook. Exactly one of socket or webhook.
	Webhook *string `pulumi:"webhook"`
}

// The set of arguments for constructing a Hook resource.
type HookArgs struct {
	// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
	At pulumi.StringPtrInput
	// Whether this hook is the default for its stage. Write-only (not echoed by reads).
	Default pulumi.BoolPtrInput
	// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
	Global pulumi.BoolPtrInput
	// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
	Kind pulumi.StringInput
	// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
	Name pulumi.StringPtrInput
	// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
	OnEmpty pulumi.StringPtrInput
	// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
	OnError pulumi.StringPtrInput
	// Ordering priority within a stage. Defaults to 0.
	Priority pulumi.IntPtrInput
	// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
	Prompt pulumi.StringPtrInput
	// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
	Settings pulumi.StringPtrInput
	// Unix socket path to the hook process. Exactly one of socket or webhook.
	Socket pulumi.StringPtrInput
	// Per-call timeout in milliseconds. Defaults to 1.
	TimeoutMs pulumi.IntPtrInput
	// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
	User pulumi.StringPtrInput
	// Webhook URL for the hook. Exactly one of socket or webhook.
	Webhook pulumi.StringPtrInput
}

func (HookArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hookArgs)(nil)).Elem()
}

type HookInput interface {
	pulumi.Input

	ToHookOutput() HookOutput
	ToHookOutputWithContext(ctx context.Context) HookOutput
}

func (*Hook) ElementType() reflect.Type {
	return reflect.TypeOf((**Hook)(nil)).Elem()
}

func (i *Hook) ToHookOutput() HookOutput {
	return i.ToHookOutputWithContext(context.Background())
}

func (i *Hook) ToHookOutputWithContext(ctx context.Context) HookOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookOutput)
}

// HookArrayInput is an input type that accepts HookArray and HookArrayOutput values.
// You can construct a concrete instance of `HookArrayInput` via:
//
//	HookArray{ HookArgs{...} }
type HookArrayInput interface {
	pulumi.Input

	ToHookArrayOutput() HookArrayOutput
	ToHookArrayOutputWithContext(context.Context) HookArrayOutput
}

type HookArray []HookInput

func (HookArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Hook)(nil)).Elem()
}

func (i HookArray) ToHookArrayOutput() HookArrayOutput {
	return i.ToHookArrayOutputWithContext(context.Background())
}

func (i HookArray) ToHookArrayOutputWithContext(ctx context.Context) HookArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookArrayOutput)
}

// HookMapInput is an input type that accepts HookMap and HookMapOutput values.
// You can construct a concrete instance of `HookMapInput` via:
//
//	HookMap{ "key": HookArgs{...} }
type HookMapInput interface {
	pulumi.Input

	ToHookMapOutput() HookMapOutput
	ToHookMapOutputWithContext(context.Context) HookMapOutput
}

type HookMap map[string]HookInput

func (HookMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Hook)(nil)).Elem()
}

func (i HookMap) ToHookMapOutput() HookMapOutput {
	return i.ToHookMapOutputWithContext(context.Background())
}

func (i HookMap) ToHookMapOutputWithContext(ctx context.Context) HookMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookMapOutput)
}

type HookOutput struct{ *pulumi.OutputState }

func (HookOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Hook)(nil)).Elem()
}

func (o HookOutput) ToHookOutput() HookOutput {
	return o
}

func (o HookOutput) ToHookOutputWithContext(ctx context.Context) HookOutput {
	return o
}

// Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
func (o HookOutput) At() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.At }).(pulumi.StringPtrOutput)
}

// Whether this hook is the default for its stage. Write-only (not echoed by reads).
func (o HookOutput) Default() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.BoolPtrOutput { return v.Default }).(pulumi.BoolPtrOutput)
}

// Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
func (o HookOutput) Global() pulumi.BoolOutput {
	return o.ApplyT(func(v *Hook) pulumi.BoolOutput { return v.Global }).(pulumi.BoolOutput)
}

// Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
func (o HookOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
func (o HookOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
func (o HookOutput) OnEmpty() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.OnEmpty }).(pulumi.StringPtrOutput)
}

// Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
func (o HookOutput) OnError() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.OnError }).(pulumi.StringOutput)
}

// Ordering priority within a stage. Defaults to 0.
func (o HookOutput) Priority() pulumi.IntOutput {
	return o.ApplyT(func(v *Hook) pulumi.IntOutput { return v.Priority }).(pulumi.IntOutput)
}

// Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
func (o HookOutput) Prompt() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Prompt }).(pulumi.StringOutput)
}

// Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
func (o HookOutput) Settings() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Settings }).(pulumi.StringOutput)
}

// Unix socket path to the hook process. Exactly one of socket or webhook.
func (o HookOutput) Socket() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.Socket }).(pulumi.StringPtrOutput)
}

// Per-call timeout in milliseconds. Defaults to 1.
func (o HookOutput) TimeoutMs() pulumi.IntOutput {
	return o.ApplyT(func(v *Hook) pulumi.IntOutput { return v.TimeoutMs }).(pulumi.IntOutput)
}

// Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
func (o HookOutput) User() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.User }).(pulumi.StringOutput)
}

// Webhook URL for the hook. Exactly one of socket or webhook.
func (o HookOutput) Webhook() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.Webhook }).(pulumi.StringPtrOutput)
}

type HookArrayOutput struct{ *pulumi.OutputState }

func (HookArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Hook)(nil)).Elem()
}

func (o HookArrayOutput) ToHookArrayOutput() HookArrayOutput {
	return o
}

func (o HookArrayOutput) ToHookArrayOutputWithContext(ctx context.Context) HookArrayOutput {
	return o
}

func (o HookArrayOutput) Index(i pulumi.IntInput) HookOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Hook {
		return vs[0].([]*Hook)[vs[1].(int)]
	}).(HookOutput)
}

type HookMapOutput struct{ *pulumi.OutputState }

func (HookMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Hook)(nil)).Elem()
}

func (o HookMapOutput) ToHookMapOutput() HookMapOutput {
	return o
}

func (o HookMapOutput) ToHookMapOutputWithContext(ctx context.Context) HookMapOutput {
	return o
}

func (o HookMapOutput) MapIndex(k pulumi.StringInput) HookOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Hook {
		return vs[0].(map[string]*Hook)[vs[1].(string)]
	}).(HookOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HookInput)(nil)).Elem(), &Hook{})
	pulumi.RegisterInputType(reflect.TypeOf((*HookArrayInput)(nil)).Elem(), HookArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HookMapInput)(nil)).Elem(), HookMap{})
	pulumi.RegisterOutputType(HookOutput{})
	pulumi.RegisterOutputType(HookArrayOutput{})
	pulumi.RegisterOutputType(HookMapOutput{})
}
