// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package busbar

import (
	"context"
	"reflect"

	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the busbar package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
	CaCertPem pulumi.StringPtrOutput `pulumi:"caCertPem"`
	// PEM-encoded client certificate for mTLS against a cert-gated admin plane.
	ClientCertPem pulumi.StringPtrOutput `pulumi:"clientCertPem"`
	// PEM-encoded private key for client_cert_pem.
	ClientKeyPem pulumi.StringPtrOutput `pulumi:"clientKeyPem"`
	// Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
	Endpoint pulumi.StringPtrOutput `pulumi:"endpoint"`
	// Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
	Token pulumi.StringPtrOutput `pulumi:"token"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.Endpoint == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "BUSBAR_ENDPOINT"); d != nil {
			args.Endpoint = pulumi.StringPtr(d.(string))
		}
	}
	if args.Token == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "BUSBAR_ADMIN_TOKEN"); d != nil {
			args.Token = pulumi.StringPtr(d.(string))
		}
	}
	if args.ClientKeyPem != nil {
		args.ClientKeyPem = pulumi.ToSecret(args.ClientKeyPem).(pulumi.StringPtrInput)
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientKeyPem",
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:busbar", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
	CaCertPem *string `pulumi:"caCertPem"`
	// PEM-encoded client certificate for mTLS against a cert-gated admin plane.
	ClientCertPem *string `pulumi:"clientCertPem"`
	// PEM-encoded private key for client_cert_pem.
	ClientKeyPem *string `pulumi:"clientKeyPem"`
	// Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
	Endpoint *string `pulumi:"endpoint"`
	// Skip TLS certificate verification. Development only; never use against production.
	Insecure *bool `pulumi:"insecure"`
	// Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
	Token *string `pulumi:"token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
	CaCertPem pulumi.StringPtrInput
	// PEM-encoded client certificate for mTLS against a cert-gated admin plane.
	ClientCertPem pulumi.StringPtrInput
	// PEM-encoded private key for client_cert_pem.
	ClientKeyPem pulumi.StringPtrInput
	// Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
	Endpoint pulumi.StringPtrInput
	// Skip TLS certificate verification. Development only; never use against production.
	Insecure pulumi.BoolPtrInput
	// Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
	Token pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:busbar/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
func (o ProviderOutput) CaCertPem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.CaCertPem }).(pulumi.StringPtrOutput)
}

// PEM-encoded client certificate for mTLS against a cert-gated admin plane.
func (o ProviderOutput) ClientCertPem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientCertPem }).(pulumi.StringPtrOutput)
}

// PEM-encoded private key for client_cert_pem.
func (o ProviderOutput) ClientKeyPem() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ClientKeyPem }).(pulumi.StringPtrOutput)
}

// Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
func (o ProviderOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Endpoint }).(pulumi.StringPtrOutput)
}

// Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
func (o ProviderOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
