// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package busbar

import (
	"context"
	"reflect"

	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VirtualKey struct {
	pulumi.CustomResourceState

	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools pulumi.StringArrayOutput `pulumi:"allowedPools"`
	// AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
	AwsAccessKeyId pulumi.StringOutput `pulumi:"awsAccessKeyId"`
	// AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey pulumi.StringOutput `pulumi:"awsSecretAccessKey"`
	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod pulumi.StringOutput `pulumi:"budgetPeriod"`
	// Epoch seconds the key was minted.
	CreatedAt pulumi.IntOutput `pulumi:"createdAt"`
	// Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrOutput `pulumi:"issueAwsCredential"`
	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents pulumi.IntPtrOutput `pulumi:"maxBudgetCents"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringOutput `pulumi:"name"`
	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit pulumi.IntPtrOutput `pulumi:"rpmLimit"`
	// The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
	Secret pulumi.StringOutput `pulumi:"secret"`
	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit pulumi.IntPtrOutput `pulumi:"tpmLimit"`
}

// NewVirtualKey registers a new resource with the given unique name, arguments, and options.
func NewVirtualKey(ctx *pulumi.Context,
	name string, args *VirtualKeyArgs, opts ...pulumi.ResourceOption) (*VirtualKey, error) {
	if args == nil {
		args = &VirtualKeyArgs{}
	}

	secrets := pulumi.AdditionalSecretOutputs([]string{
		"awsSecretAccessKey",
		"secret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VirtualKey
	err := ctx.RegisterResource("busbar:index/virtualKey:VirtualKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVirtualKey gets an existing VirtualKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVirtualKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VirtualKeyState, opts ...pulumi.ResourceOption) (*VirtualKey, error) {
	var resource VirtualKey
	err := ctx.ReadResource("busbar:index/virtualKey:VirtualKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VirtualKey resources.
type virtualKeyState struct {
	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools []string `pulumi:"allowedPools"`
	// AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
	AwsAccessKeyId *string `pulumi:"awsAccessKeyId"`
	// AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey *string `pulumi:"awsSecretAccessKey"`
	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod *string `pulumi:"budgetPeriod"`
	// Epoch seconds the key was minted.
	CreatedAt *int `pulumi:"createdAt"`
	// Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
	Enabled *bool `pulumi:"enabled"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `pulumi:"issueAwsCredential"`
	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents *int `pulumi:"maxBudgetCents"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `pulumi:"name"`
	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit *int `pulumi:"rpmLimit"`
	// The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
	Secret *string `pulumi:"secret"`
	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit *int `pulumi:"tpmLimit"`
}

type VirtualKeyState struct {
	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools pulumi.StringArrayInput
	// AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
	AwsAccessKeyId pulumi.StringPtrInput
	// AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey pulumi.StringPtrInput
	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod pulumi.StringPtrInput
	// Epoch seconds the key was minted.
	CreatedAt pulumi.IntPtrInput
	// Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
	Enabled pulumi.BoolPtrInput
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrInput
	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents pulumi.IntPtrInput
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringPtrInput
	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit pulumi.IntPtrInput
	// The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
	Secret pulumi.StringPtrInput
	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit pulumi.IntPtrInput
}

func (VirtualKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualKeyState)(nil)).Elem()
}

type virtualKeyArgs struct {
	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools []string `pulumi:"allowedPools"`
	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod *string `pulumi:"budgetPeriod"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `pulumi:"issueAwsCredential"`
	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents *int `pulumi:"maxBudgetCents"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `pulumi:"name"`
	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit *int `pulumi:"rpmLimit"`
	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit *int `pulumi:"tpmLimit"`
}

// The set of arguments for constructing a VirtualKey resource.
type VirtualKeyArgs struct {
	// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
	AllowedPools pulumi.StringArrayInput
	// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
	BudgetPeriod pulumi.StringPtrInput
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrInput
	// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
	MaxBudgetCents pulumi.IntPtrInput
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringPtrInput
	// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	RpmLimit pulumi.IntPtrInput
	// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
	TpmLimit pulumi.IntPtrInput
}

func (VirtualKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualKeyArgs)(nil)).Elem()
}

type VirtualKeyInput interface {
	pulumi.Input

	ToVirtualKeyOutput() VirtualKeyOutput
	ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput
}

func (*VirtualKey) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualKey)(nil)).Elem()
}

func (i *VirtualKey) ToVirtualKeyOutput() VirtualKeyOutput {
	return i.ToVirtualKeyOutputWithContext(context.Background())
}

func (i *VirtualKey) ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyOutput)
}

// VirtualKeyArrayInput is an input type that accepts VirtualKeyArray and VirtualKeyArrayOutput values.
// You can construct a concrete instance of `VirtualKeyArrayInput` via:
//
//	VirtualKeyArray{ VirtualKeyArgs{...} }
type VirtualKeyArrayInput interface {
	pulumi.Input

	ToVirtualKeyArrayOutput() VirtualKeyArrayOutput
	ToVirtualKeyArrayOutputWithContext(context.Context) VirtualKeyArrayOutput
}

type VirtualKeyArray []VirtualKeyInput

func (VirtualKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VirtualKey)(nil)).Elem()
}

func (i VirtualKeyArray) ToVirtualKeyArrayOutput() VirtualKeyArrayOutput {
	return i.ToVirtualKeyArrayOutputWithContext(context.Background())
}

func (i VirtualKeyArray) ToVirtualKeyArrayOutputWithContext(ctx context.Context) VirtualKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyArrayOutput)
}

// VirtualKeyMapInput is an input type that accepts VirtualKeyMap and VirtualKeyMapOutput values.
// You can construct a concrete instance of `VirtualKeyMapInput` via:
//
//	VirtualKeyMap{ "key": VirtualKeyArgs{...} }
type VirtualKeyMapInput interface {
	pulumi.Input

	ToVirtualKeyMapOutput() VirtualKeyMapOutput
	ToVirtualKeyMapOutputWithContext(context.Context) VirtualKeyMapOutput
}

type VirtualKeyMap map[string]VirtualKeyInput

func (VirtualKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VirtualKey)(nil)).Elem()
}

func (i VirtualKeyMap) ToVirtualKeyMapOutput() VirtualKeyMapOutput {
	return i.ToVirtualKeyMapOutputWithContext(context.Background())
}

func (i VirtualKeyMap) ToVirtualKeyMapOutputWithContext(ctx context.Context) VirtualKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyMapOutput)
}

type VirtualKeyOutput struct{ *pulumi.OutputState }

func (VirtualKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualKey)(nil)).Elem()
}

func (o VirtualKeyOutput) ToVirtualKeyOutput() VirtualKeyOutput {
	return o
}

func (o VirtualKeyOutput) ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput {
	return o
}

// Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
func (o VirtualKeyOutput) AllowedPools() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringArrayOutput { return v.AllowedPools }).(pulumi.StringArrayOutput)
}

// AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
func (o VirtualKeyOutput) AwsAccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.AwsAccessKeyId }).(pulumi.StringOutput)
}

// AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
func (o VirtualKeyOutput) AwsSecretAccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.AwsSecretAccessKey }).(pulumi.StringOutput)
}

// Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
func (o VirtualKeyOutput) BudgetPeriod() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.BudgetPeriod }).(pulumi.StringOutput)
}

// Epoch seconds the key was minted.
func (o VirtualKeyOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntOutput { return v.CreatedAt }).(pulumi.IntOutput)
}

// Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
func (o VirtualKeyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
func (o VirtualKeyOutput) IssueAwsCredential() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.BoolPtrOutput { return v.IssueAwsCredential }).(pulumi.BoolPtrOutput)
}

// Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
func (o VirtualKeyOutput) MaxBudgetCents() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntPtrOutput { return v.MaxBudgetCents }).(pulumi.IntPtrOutput)
}

// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
func (o VirtualKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
func (o VirtualKeyOutput) RpmLimit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntPtrOutput { return v.RpmLimit }).(pulumi.IntPtrOutput)
}

// The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
func (o VirtualKeyOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

// Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
func (o VirtualKeyOutput) TpmLimit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntPtrOutput { return v.TpmLimit }).(pulumi.IntPtrOutput)
}

type VirtualKeyArrayOutput struct{ *pulumi.OutputState }

func (VirtualKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VirtualKey)(nil)).Elem()
}

func (o VirtualKeyArrayOutput) ToVirtualKeyArrayOutput() VirtualKeyArrayOutput {
	return o
}

func (o VirtualKeyArrayOutput) ToVirtualKeyArrayOutputWithContext(ctx context.Context) VirtualKeyArrayOutput {
	return o
}

func (o VirtualKeyArrayOutput) Index(i pulumi.IntInput) VirtualKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VirtualKey {
		return vs[0].([]*VirtualKey)[vs[1].(int)]
	}).(VirtualKeyOutput)
}

type VirtualKeyMapOutput struct{ *pulumi.OutputState }

func (VirtualKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VirtualKey)(nil)).Elem()
}

func (o VirtualKeyMapOutput) ToVirtualKeyMapOutput() VirtualKeyMapOutput {
	return o
}

func (o VirtualKeyMapOutput) ToVirtualKeyMapOutputWithContext(ctx context.Context) VirtualKeyMapOutput {
	return o
}

func (o VirtualKeyMapOutput) MapIndex(k pulumi.StringInput) VirtualKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VirtualKey {
		return vs[0].(map[string]*VirtualKey)[vs[1].(string)]
	}).(VirtualKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyInput)(nil)).Elem(), &VirtualKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyArrayInput)(nil)).Elem(), VirtualKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyMapInput)(nil)).Elem(), VirtualKeyMap{})
	pulumi.RegisterOutputType(VirtualKeyOutput{})
	pulumi.RegisterOutputType(VirtualKeyArrayOutput{})
	pulumi.RegisterOutputType(VirtualKeyMapOutput{})
}
