// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package busbar

import (
	"context"
	"reflect"

	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A governance virtual key (busbar >= 1.5.0): a mintable, revocable, EXPIRING signed-token credential, optionally bound to a `groups:` bucket that carries all budget and rate enforcement (POST/GET/PATCH/DELETE /api/v1/admin/keys). The signed token is returned by busbar only once, at creation, and is stored in state as a sensitive value; refreshes update metadata (group/enabled/state) but never the token. Requires governance to be enabled on the gateway.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Mint a governance virtual key (busbar >= 1.5.0): a signed, expiring token,
//			// bound to a `groups:` bucket that carries all budget/rate enforcement, scoped
//			// to the "smart" pool. The signed token is returned only once, at creation, and
//			// stored in state as a sensitive value.
//			app, err := busbar.NewVirtualKey(ctx, "app", &busbar.VirtualKeyArgs{
//				Name:  pulumi.String("checkout-service"),
//				Group: pulumi.String("team-checkout"),
//				AllowedPools: pulumi.StringArray{
//					pulumi.String("smart"),
//				},
//				ExpiresIn: pulumi.String("30d"),
//				Labels: pulumi.StringMap{
//					"service": pulumi.String("checkout"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("appKeyToken", app.Token)
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Virtual keys are imported by their server-assigned id (the signed token
// cannot be recovered — it is create-only — and stays null after import).
//
// ```sh
// $ pulumi import busbar:index/virtualKey:VirtualKey app vk_0123456789abcdef
// ```
type VirtualKey struct {
	pulumi.CustomResourceState

	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools pulumi.StringArrayOutput `pulumi:"allowedPools"`
	// AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
	AwsAccessKeyId pulumi.StringOutput `pulumi:"awsAccessKeyId"`
	// AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey pulumi.StringOutput `pulumi:"awsSecretAccessKey"`
	// Epoch seconds the key was minted.
	CreatedAt pulumi.IntOutput `pulumi:"createdAt"`
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt pulumi.IntOutput `pulumi:"expiresAt"`
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn pulumi.StringPtrOutput `pulumi:"expiresIn"`
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group pulumi.StringPtrOutput `pulumi:"group"`
	// Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
	GroupProvisioned pulumi.BoolOutput `pulumi:"groupProvisioned"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrOutput `pulumi:"issueAwsCredential"`
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringOutput `pulumi:"name"`
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent pulumi.StringPtrOutput `pulumi:"parent"`
	// Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
	State pulumi.StringOutput `pulumi:"state"`
	// The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewVirtualKey registers a new resource with the given unique name, arguments, and options.
func NewVirtualKey(ctx *pulumi.Context,
	name string, args *VirtualKeyArgs, opts ...pulumi.ResourceOption) (*VirtualKey, error) {
	if args == nil {
		args = &VirtualKeyArgs{}
	}

	secrets := pulumi.AdditionalSecretOutputs([]string{
		"awsSecretAccessKey",
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VirtualKey
	err := ctx.RegisterResource("busbar:index/virtualKey:VirtualKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVirtualKey gets an existing VirtualKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVirtualKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VirtualKeyState, opts ...pulumi.ResourceOption) (*VirtualKey, error) {
	var resource VirtualKey
	err := ctx.ReadResource("busbar:index/virtualKey:VirtualKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VirtualKey resources.
type virtualKeyState struct {
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools []string `pulumi:"allowedPools"`
	// AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
	AwsAccessKeyId *string `pulumi:"awsAccessKeyId"`
	// AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey *string `pulumi:"awsSecretAccessKey"`
	// Epoch seconds the key was minted.
	CreatedAt *int `pulumi:"createdAt"`
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled *bool `pulumi:"enabled"`
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt *int `pulumi:"expiresAt"`
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn *string `pulumi:"expiresIn"`
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group *string `pulumi:"group"`
	// Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
	GroupProvisioned *bool `pulumi:"groupProvisioned"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `pulumi:"issueAwsCredential"`
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	Labels map[string]string `pulumi:"labels"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `pulumi:"name"`
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent *string `pulumi:"parent"`
	// Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
	State *string `pulumi:"state"`
	// The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
	Token *string `pulumi:"token"`
}

type VirtualKeyState struct {
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools pulumi.StringArrayInput
	// AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
	AwsAccessKeyId pulumi.StringPtrInput
	// AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
	AwsSecretAccessKey pulumi.StringPtrInput
	// Epoch seconds the key was minted.
	CreatedAt pulumi.IntPtrInput
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled pulumi.BoolPtrInput
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt pulumi.IntPtrInput
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn pulumi.StringPtrInput
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group pulumi.StringPtrInput
	// Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
	GroupProvisioned pulumi.BoolPtrInput
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrInput
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	Labels pulumi.StringMapInput
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringPtrInput
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent pulumi.StringPtrInput
	// Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
	State pulumi.StringPtrInput
	// The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
	Token pulumi.StringPtrInput
}

func (VirtualKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualKeyState)(nil)).Elem()
}

type virtualKeyArgs struct {
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools []string `pulumi:"allowedPools"`
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled *bool `pulumi:"enabled"`
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt *int `pulumi:"expiresAt"`
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn *string `pulumi:"expiresIn"`
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group *string `pulumi:"group"`
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential *bool `pulumi:"issueAwsCredential"`
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	Labels map[string]string `pulumi:"labels"`
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name *string `pulumi:"name"`
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent *string `pulumi:"parent"`
}

// The set of arguments for constructing a VirtualKey resource.
type VirtualKeyArgs struct {
	// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
	AllowedPools pulumi.StringArrayInput
	// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
	Enabled pulumi.BoolPtrInput
	// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
	ExpiresAt pulumi.IntPtrInput
	// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
	ExpiresIn pulumi.StringPtrInput
	// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
	Group pulumi.StringPtrInput
	// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
	IssueAwsCredential pulumi.BoolPtrInput
	// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
	Labels pulumi.StringMapInput
	// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
	Name pulumi.StringPtrInput
	// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
	Parent pulumi.StringPtrInput
}

func (VirtualKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualKeyArgs)(nil)).Elem()
}

type VirtualKeyInput interface {
	pulumi.Input

	ToVirtualKeyOutput() VirtualKeyOutput
	ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput
}

func (*VirtualKey) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualKey)(nil)).Elem()
}

func (i *VirtualKey) ToVirtualKeyOutput() VirtualKeyOutput {
	return i.ToVirtualKeyOutputWithContext(context.Background())
}

func (i *VirtualKey) ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyOutput)
}

// VirtualKeyArrayInput is an input type that accepts VirtualKeyArray and VirtualKeyArrayOutput values.
// You can construct a concrete instance of `VirtualKeyArrayInput` via:
//
//	VirtualKeyArray{ VirtualKeyArgs{...} }
type VirtualKeyArrayInput interface {
	pulumi.Input

	ToVirtualKeyArrayOutput() VirtualKeyArrayOutput
	ToVirtualKeyArrayOutputWithContext(context.Context) VirtualKeyArrayOutput
}

type VirtualKeyArray []VirtualKeyInput

func (VirtualKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VirtualKey)(nil)).Elem()
}

func (i VirtualKeyArray) ToVirtualKeyArrayOutput() VirtualKeyArrayOutput {
	return i.ToVirtualKeyArrayOutputWithContext(context.Background())
}

func (i VirtualKeyArray) ToVirtualKeyArrayOutputWithContext(ctx context.Context) VirtualKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyArrayOutput)
}

// VirtualKeyMapInput is an input type that accepts VirtualKeyMap and VirtualKeyMapOutput values.
// You can construct a concrete instance of `VirtualKeyMapInput` via:
//
//	VirtualKeyMap{ "key": VirtualKeyArgs{...} }
type VirtualKeyMapInput interface {
	pulumi.Input

	ToVirtualKeyMapOutput() VirtualKeyMapOutput
	ToVirtualKeyMapOutputWithContext(context.Context) VirtualKeyMapOutput
}

type VirtualKeyMap map[string]VirtualKeyInput

func (VirtualKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VirtualKey)(nil)).Elem()
}

func (i VirtualKeyMap) ToVirtualKeyMapOutput() VirtualKeyMapOutput {
	return i.ToVirtualKeyMapOutputWithContext(context.Background())
}

func (i VirtualKeyMap) ToVirtualKeyMapOutputWithContext(ctx context.Context) VirtualKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualKeyMapOutput)
}

type VirtualKeyOutput struct{ *pulumi.OutputState }

func (VirtualKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualKey)(nil)).Elem()
}

func (o VirtualKeyOutput) ToVirtualKeyOutput() VirtualKeyOutput {
	return o
}

func (o VirtualKeyOutput) ToVirtualKeyOutputWithContext(ctx context.Context) VirtualKeyOutput {
	return o
}

// Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
func (o VirtualKeyOutput) AllowedPools() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringArrayOutput { return v.AllowedPools }).(pulumi.StringArrayOutput)
}

// AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
func (o VirtualKeyOutput) AwsAccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.AwsAccessKeyId }).(pulumi.StringOutput)
}

// AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
func (o VirtualKeyOutput) AwsSecretAccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.AwsSecretAccessKey }).(pulumi.StringOutput)
}

// Epoch seconds the key was minted.
func (o VirtualKeyOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntOutput { return v.CreatedAt }).(pulumi.IntOutput)
}

// Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
func (o VirtualKeyOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
func (o VirtualKeyOutput) ExpiresAt() pulumi.IntOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.IntOutput { return v.ExpiresAt }).(pulumi.IntOutput)
}

// Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
func (o VirtualKeyOutput) ExpiresIn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringPtrOutput { return v.ExpiresIn }).(pulumi.StringPtrOutput)
}

// The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
func (o VirtualKeyOutput) Group() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringPtrOutput { return v.Group }).(pulumi.StringPtrOutput)
}

// Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
func (o VirtualKeyOutput) GroupProvisioned() pulumi.BoolOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.BoolOutput { return v.GroupProvisioned }).(pulumi.BoolOutput)
}

// When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
func (o VirtualKeyOutput) IssueAwsCredential() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.BoolPtrOutput { return v.IssueAwsCredential }).(pulumi.BoolPtrOutput)
}

// Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
func (o VirtualKeyOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
func (o VirtualKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
func (o VirtualKeyOutput) Parent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringPtrOutput { return v.Parent }).(pulumi.StringPtrOutput)
}

// Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
func (o VirtualKeyOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
func (o VirtualKeyOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualKey) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type VirtualKeyArrayOutput struct{ *pulumi.OutputState }

func (VirtualKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VirtualKey)(nil)).Elem()
}

func (o VirtualKeyArrayOutput) ToVirtualKeyArrayOutput() VirtualKeyArrayOutput {
	return o
}

func (o VirtualKeyArrayOutput) ToVirtualKeyArrayOutputWithContext(ctx context.Context) VirtualKeyArrayOutput {
	return o
}

func (o VirtualKeyArrayOutput) Index(i pulumi.IntInput) VirtualKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VirtualKey {
		return vs[0].([]*VirtualKey)[vs[1].(int)]
	}).(VirtualKeyOutput)
}

type VirtualKeyMapOutput struct{ *pulumi.OutputState }

func (VirtualKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VirtualKey)(nil)).Elem()
}

func (o VirtualKeyMapOutput) ToVirtualKeyMapOutput() VirtualKeyMapOutput {
	return o
}

func (o VirtualKeyMapOutput) ToVirtualKeyMapOutputWithContext(ctx context.Context) VirtualKeyMapOutput {
	return o
}

func (o VirtualKeyMapOutput) MapIndex(k pulumi.StringInput) VirtualKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VirtualKey {
		return vs[0].(map[string]*VirtualKey)[vs[1].(string)]
	}).(VirtualKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyInput)(nil)).Elem(), &VirtualKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyArrayInput)(nil)).Elem(), VirtualKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualKeyMapInput)(nil)).Elem(), VirtualKeyMap{})
	pulumi.RegisterOutputType(VirtualKeyOutput{})
	pulumi.RegisterOutputType(VirtualKeyArrayOutput{})
	pulumi.RegisterOutputType(VirtualKeyMapOutput{})
}
