// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("busbar");

/**
 * PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
 */
export declare const caCertPem: string | undefined;
Object.defineProperty(exports, "caCertPem", {
    get() {
        return __config.get("caCertPem");
    },
    enumerable: true,
});

/**
 * PEM-encoded client certificate for mTLS against a cert-gated admin plane.
 */
export declare const clientCertPem: string | undefined;
Object.defineProperty(exports, "clientCertPem", {
    get() {
        return __config.get("clientCertPem");
    },
    enumerable: true,
});

/**
 * PEM-encoded private key for client_cert_pem.
 */
export declare const clientKeyPem: string | undefined;
Object.defineProperty(exports, "clientKeyPem", {
    get() {
        return __config.get("clientKeyPem");
    },
    enumerable: true,
});

/**
 * Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint") ?? utilities.getEnv("BUSBAR_ENDPOINT");
    },
    enumerable: true,
});

/**
 * Skip TLS certificate verification. Development only; never use against production.
 */
export declare const insecure: boolean | undefined;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure");
    },
    enumerable: true,
});

/**
 * Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? utilities.getEnv("BUSBAR_ADMIN_TOKEN");
    },
    enumerable: true,
});

