// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/getbusbar/pulumi-busbar/sdk/go/busbar/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
func GetCaCertPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "busbar:caCertPem")
}

// PEM-encoded client certificate for mTLS against a cert-gated admin plane.
func GetClientCertPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "busbar:clientCertPem")
}

// PEM-encoded private key for client_cert_pem.
func GetClientKeyPem(ctx *pulumi.Context) string {
	return config.Get(ctx, "busbar:clientKeyPem")
}

// Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
func GetEndpoint(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "busbar:endpoint")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BUSBAR_ENDPOINT"); d != nil {
		value = d.(string)
	}
	return value
}

// Skip TLS certificate verification. Development only; never use against production.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "busbar:insecure")
}

// Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "busbar:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BUSBAR_ADMIN_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
