# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .config_ import *
from .get_info import *
from .hook import *
from .provider import *
from .virtual_key import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_busbar.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_busbar.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "busbar",
  "mod": "index/config",
  "fqn": "pulumi_busbar",
  "classes": {
   "busbar:index/config:Config": "Config"
  }
 },
 {
  "pkg": "busbar",
  "mod": "index/hook",
  "fqn": "pulumi_busbar",
  "classes": {
   "busbar:index/hook:Hook": "Hook"
  }
 },
 {
  "pkg": "busbar",
  "mod": "index/virtualKey",
  "fqn": "pulumi_busbar",
  "classes": {
   "busbar:index/virtualKey:VirtualKey": "VirtualKey"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "busbar",
  "token": "pulumi:providers:busbar",
  "fqn": "pulumi_busbar",
  "class": "Provider"
 }
]
"""
)
