# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ConfigArgs', 'Config']

@pulumi.input_type
class ConfigArgs:
    def __init__(__self__, *,
                 document: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a Config resource.

        :param pulumi.Input[_builtins.str] document: The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        pulumi.set(__self__, "document", document)

    @_builtins.property
    @pulumi.getter
    def document(self) -> pulumi.Input[_builtins.str]:
        """
        The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        return pulumi.get(self, "document")

    @document.setter
    def document(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "document", value)


@pulumi.input_type
class _ConfigState:
    def __init__(__self__, *,
                 config_version: pulumi.Input[Optional[_builtins.int]] = None,
                 document: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Config resources.

        :param pulumi.Input[_builtins.int] config_version: The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
        :param pulumi.Input[_builtins.str] document: The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        if config_version is not None:
            pulumi.set(__self__, "config_version", config_version)
        if document is not None:
            pulumi.set(__self__, "document", document)

    @_builtins.property
    @pulumi.getter(name="configVersion")
    def config_version(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
        """
        return pulumi.get(self, "config_version")

    @config_version.setter
    def config_version(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "config_version", value)

    @_builtins.property
    @pulumi.getter
    def document(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        return pulumi.get(self, "document")

    @document.setter
    def document(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "document", value)


@pulumi.type_token("busbar:index/config:Config")
class Config(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 document: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A GitOps singleton that owns the running busbar config and applies it wholesale (POST /api/v1/admin/config/apply). Manage at most ONE of these per gateway. The document is the full JSON config payload busbar boots from ({"config": {...}, "providers": {...}}); applying it bumps config_version. Applies are LIVE-ONLY by default — they revert to disk truth on the next reload or restart unless the gateway persists an overlay. Destroying this resource is a no-op on the gateway (there is no unapply); it only drops Terraform's tracking.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_busbar as busbar

        # GitOps singleton: apply the whole running config document. Manage AT MOST ONE
        # busbar_config per gateway. The document is the JSON form of busbar's 1.5.0
        # config syntax, an envelope of { config = {config.yaml deploy block},
        # providers = {providers.yaml document} }.
        #
        # Applies are live-only by default: they revert to disk truth on the next reload
        # or restart unless the gateway persists an overlay. Destroying this resource is a
        # no-op on the gateway (there is no "unapply"); it only drops Terraform's tracking.
        running = busbar.Config("running", document=json.dumps({
            "config": {
                "auth": {
                    "chain": ["keys"],
                    "admin_auth": [{
                        "admin-tokens": {
                            "token": {
                                "env": "BUSBAR_ADMIN_TOKEN",
                            },
                        },
                    }],
                },
                "providers": {
                    "anthropic": {
                        "api_key": {
                            "env": "ANTHROPIC_API_KEY",
                        },
                    },
                },
                "models": {
                    "claude-sonnet": {
                        "provider": "anthropic",
                    },
                },
                "groups": {
                    "team-checkout": {},
                },
            },
            "providers": {
                "anthropic": {
                    "protocol": "anthropic",
                    "base_url": "https://api.anthropic.com",
                },
            },
        }))
        pulumi.export("configVersion", running.config_version)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        The config singleton has a fixed import id. The document is not recoverable
        (GET /config is a redacted projection), so supply the matching `document` in
        your configuration after import; only config_version is read live.

        ```sh
        $ pulumi import busbar:index/config:Config running config
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] document: The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ConfigArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A GitOps singleton that owns the running busbar config and applies it wholesale (POST /api/v1/admin/config/apply). Manage at most ONE of these per gateway. The document is the full JSON config payload busbar boots from ({"config": {...}, "providers": {...}}); applying it bumps config_version. Applies are LIVE-ONLY by default — they revert to disk truth on the next reload or restart unless the gateway persists an overlay. Destroying this resource is a no-op on the gateway (there is no unapply); it only drops Terraform's tracking.

        ## Example Usage

        ```python
        import pulumi
        import json
        import pulumi_busbar as busbar

        # GitOps singleton: apply the whole running config document. Manage AT MOST ONE
        # busbar_config per gateway. The document is the JSON form of busbar's 1.5.0
        # config syntax, an envelope of { config = {config.yaml deploy block},
        # providers = {providers.yaml document} }.
        #
        # Applies are live-only by default: they revert to disk truth on the next reload
        # or restart unless the gateway persists an overlay. Destroying this resource is a
        # no-op on the gateway (there is no "unapply"); it only drops Terraform's tracking.
        running = busbar.Config("running", document=json.dumps({
            "config": {
                "auth": {
                    "chain": ["keys"],
                    "admin_auth": [{
                        "admin-tokens": {
                            "token": {
                                "env": "BUSBAR_ADMIN_TOKEN",
                            },
                        },
                    }],
                },
                "providers": {
                    "anthropic": {
                        "api_key": {
                            "env": "ANTHROPIC_API_KEY",
                        },
                    },
                },
                "models": {
                    "claude-sonnet": {
                        "provider": "anthropic",
                    },
                },
                "groups": {
                    "team-checkout": {},
                },
            },
            "providers": {
                "anthropic": {
                    "protocol": "anthropic",
                    "base_url": "https://api.anthropic.com",
                },
            },
        }))
        pulumi.export("configVersion", running.config_version)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        The config singleton has a fixed import id. The document is not recoverable
        (GET /config is a redacted projection), so supply the matching `document` in
        your configuration after import; only config_version is read live.

        ```sh
        $ pulumi import busbar:index/config:Config running config
        ```


        :param str resource_name: The name of the resource.
        :param ConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 document: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ConfigArgs.__new__(ConfigArgs)

            if document is None and not opts.urn:
                raise TypeError("Missing required property 'document'")
            __props__.__dict__["document"] = document
            __props__.__dict__["config_version"] = None
        super(Config, __self__).__init__(
            'busbar:index/config:Config',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            config_version: pulumi.Input[Optional[_builtins.int]] = None,
            document: pulumi.Input[Optional[_builtins.str]] = None) -> 'Config':
        """
        Get an existing Config resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] config_version: The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
        :param pulumi.Input[_builtins.str] document: The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ConfigState.__new__(_ConfigState)

        __props__.__dict__["config_version"] = config_version
        __props__.__dict__["document"] = document
        return Config(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="configVersion")
    def config_version(self) -> pulumi.Output[_builtins.int]:
        """
        The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
        """
        return pulumi.get(self, "config_version")

    @_builtins.property
    @pulumi.getter
    def document(self) -> pulumi.Output[_builtins.str]:
        """
        The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
        """
        return pulumi.get(self, "document")

