# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetInfoResult',
    'AwaitableGetInfoResult',
    'get_info',
    'get_info_output',
]

@pulumi.output_type
class GetInfoResult:
    """
    A collection of values returned by getInfo.
    """
    def __init__(__self__, auth_modules=None, config_persistence=None, config_version=None, hook_plugins=None, id=None, models=None, pools=None, providers=None, started_at=None, uptime_seconds=None, version=None, weighted_floor=None):
        if auth_modules and not isinstance(auth_modules, list):
            raise TypeError("Expected argument 'auth_modules' to be a list")
        pulumi.set(__self__, "auth_modules", auth_modules)
        if config_persistence and not isinstance(config_persistence, bool):
            raise TypeError("Expected argument 'config_persistence' to be a bool")
        pulumi.set(__self__, "config_persistence", config_persistence)
        if config_version and not isinstance(config_version, int):
            raise TypeError("Expected argument 'config_version' to be a int")
        pulumi.set(__self__, "config_version", config_version)
        if hook_plugins and not isinstance(hook_plugins, list):
            raise TypeError("Expected argument 'hook_plugins' to be a list")
        pulumi.set(__self__, "hook_plugins", hook_plugins)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if models and not isinstance(models, int):
            raise TypeError("Expected argument 'models' to be a int")
        pulumi.set(__self__, "models", models)
        if pools and not isinstance(pools, int):
            raise TypeError("Expected argument 'pools' to be a int")
        pulumi.set(__self__, "pools", pools)
        if providers and not isinstance(providers, int):
            raise TypeError("Expected argument 'providers' to be a int")
        pulumi.set(__self__, "providers", providers)
        if started_at and not isinstance(started_at, int):
            raise TypeError("Expected argument 'started_at' to be a int")
        pulumi.set(__self__, "started_at", started_at)
        if uptime_seconds and not isinstance(uptime_seconds, int):
            raise TypeError("Expected argument 'uptime_seconds' to be a int")
        pulumi.set(__self__, "uptime_seconds", uptime_seconds)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)
        if weighted_floor and not isinstance(weighted_floor, bool):
            raise TypeError("Expected argument 'weighted_floor' to be a bool")
        pulumi.set(__self__, "weighted_floor", weighted_floor)

    @_builtins.property
    @pulumi.getter(name="authModules")
    def auth_modules(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "auth_modules")

    @_builtins.property
    @pulumi.getter(name="configPersistence")
    def config_persistence(self) -> _builtins.bool:
        return pulumi.get(self, "config_persistence")

    @_builtins.property
    @pulumi.getter(name="configVersion")
    def config_version(self) -> _builtins.int:
        return pulumi.get(self, "config_version")

    @_builtins.property
    @pulumi.getter(name="hookPlugins")
    def hook_plugins(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "hook_plugins")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def models(self) -> _builtins.int:
        return pulumi.get(self, "models")

    @_builtins.property
    @pulumi.getter
    def pools(self) -> _builtins.int:
        return pulumi.get(self, "pools")

    @_builtins.property
    @pulumi.getter
    def providers(self) -> _builtins.int:
        return pulumi.get(self, "providers")

    @_builtins.property
    @pulumi.getter(name="startedAt")
    def started_at(self) -> _builtins.int:
        return pulumi.get(self, "started_at")

    @_builtins.property
    @pulumi.getter(name="uptimeSeconds")
    def uptime_seconds(self) -> _builtins.int:
        return pulumi.get(self, "uptime_seconds")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="weightedFloor")
    def weighted_floor(self) -> _builtins.bool:
        return pulumi.get(self, "weighted_floor")


class AwaitableGetInfoResult(GetInfoResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetInfoResult(
            auth_modules=self.auth_modules,
            config_persistence=self.config_persistence,
            config_version=self.config_version,
            hook_plugins=self.hook_plugins,
            id=self.id,
            models=self.models,
            pools=self.pools,
            providers=self.providers,
            started_at=self.started_at,
            uptime_seconds=self.uptime_seconds,
            version=self.version,
            weighted_floor=self.weighted_floor)


def get_info(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetInfoResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('busbar:index/getInfo:getInfo', __args__, opts=opts, typ=GetInfoResult).value

    return AwaitableGetInfoResult(
        auth_modules=pulumi.get(__ret__, 'auth_modules'),
        config_persistence=pulumi.get(__ret__, 'config_persistence'),
        config_version=pulumi.get(__ret__, 'config_version'),
        hook_plugins=pulumi.get(__ret__, 'hook_plugins'),
        id=pulumi.get(__ret__, 'id'),
        models=pulumi.get(__ret__, 'models'),
        pools=pulumi.get(__ret__, 'pools'),
        providers=pulumi.get(__ret__, 'providers'),
        started_at=pulumi.get(__ret__, 'started_at'),
        uptime_seconds=pulumi.get(__ret__, 'uptime_seconds'),
        version=pulumi.get(__ret__, 'version'),
        weighted_floor=pulumi.get(__ret__, 'weighted_floor'))
def get_info_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetInfoResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('busbar:index/getInfo:getInfo', __args__, opts=opts, typ=GetInfoResult)
    return __ret__.apply(lambda __response__: GetInfoResult(
        auth_modules=pulumi.get(__response__, 'auth_modules'),
        config_persistence=pulumi.get(__response__, 'config_persistence'),
        config_version=pulumi.get(__response__, 'config_version'),
        hook_plugins=pulumi.get(__response__, 'hook_plugins'),
        id=pulumi.get(__response__, 'id'),
        models=pulumi.get(__response__, 'models'),
        pools=pulumi.get(__response__, 'pools'),
        providers=pulumi.get(__response__, 'providers'),
        started_at=pulumi.get(__response__, 'started_at'),
        uptime_seconds=pulumi.get(__response__, 'uptime_seconds'),
        version=pulumi.get(__response__, 'version'),
        weighted_floor=pulumi.get(__response__, 'weighted_floor')))
