# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['HookArgs', 'Hook']

@pulumi.input_type
class HookArgs:
    def __init__(__self__, *,
                 kind: pulumi.Input[_builtins.str],
                 at: pulumi.Input[Optional[_builtins.str]] = None,
                 default: pulumi.Input[Optional[_builtins.bool]] = None,
                 global_: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_empty: pulumi.Input[Optional[_builtins.str]] = None,
                 on_error: pulumi.Input[Optional[_builtins.str]] = None,
                 priority: pulumi.Input[Optional[_builtins.int]] = None,
                 prompt: pulumi.Input[Optional[_builtins.str]] = None,
                 settings: pulumi.Input[Optional[_builtins.str]] = None,
                 socket: pulumi.Input[Optional[_builtins.str]] = None,
                 timeout_ms: pulumi.Input[Optional[_builtins.int]] = None,
                 user: pulumi.Input[Optional[_builtins.str]] = None,
                 webhook: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Hook resource.

        :param pulumi.Input[_builtins.str] kind: Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] at: Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        :param pulumi.Input[_builtins.bool] default: Whether this hook is the default for its stage. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.bool] global_: Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        :param pulumi.Input[_builtins.str] name: Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] on_empty: Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.str] on_error: Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        :param pulumi.Input[_builtins.int] priority: Ordering priority within a stage. Defaults to 0.
        :param pulumi.Input[_builtins.str] prompt: Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        :param pulumi.Input[_builtins.str] settings: Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        :param pulumi.Input[_builtins.str] socket: Unix socket path to the hook process. Exactly one of socket or webhook.
        :param pulumi.Input[_builtins.int] timeout_ms: Per-call timeout in milliseconds. Defaults to 1.
        :param pulumi.Input[_builtins.str] user: Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] webhook: Webhook URL for the hook. Exactly one of socket or webhook.
        """
        pulumi.set(__self__, "kind", kind)
        if at is not None:
            pulumi.set(__self__, "at", at)
        if default is not None:
            pulumi.set(__self__, "default", default)
        if global_ is not None:
            pulumi.set(__self__, "global_", global_)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_empty is not None:
            pulumi.set(__self__, "on_empty", on_empty)
        if on_error is not None:
            pulumi.set(__self__, "on_error", on_error)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if prompt is not None:
            pulumi.set(__self__, "prompt", prompt)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)
        if socket is not None:
            pulumi.set(__self__, "socket", socket)
        if timeout_ms is not None:
            pulumi.set(__self__, "timeout_ms", timeout_ms)
        if user is not None:
            pulumi.set(__self__, "user", user)
        if webhook is not None:
            pulumi.set(__self__, "webhook", webhook)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[_builtins.str]:
        """
        Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        """
        return pulumi.get(self, "at")

    @at.setter
    def at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "at", value)

    @_builtins.property
    @pulumi.getter
    def default(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether this hook is the default for its stage. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "default")

    @default.setter
    def default(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "default", value)

    @_builtins.property
    @pulumi.getter(name="global")
    def global_(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        """
        return pulumi.get(self, "global_")

    @global_.setter
    def global_(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "global_", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="onEmpty")
    def on_empty(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "on_empty")

    @on_empty.setter
    def on_empty(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_empty", value)

    @_builtins.property
    @pulumi.getter(name="onError")
    def on_error(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        """
        return pulumi.get(self, "on_error")

    @on_error.setter
    def on_error(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_error", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Ordering priority within a stage. Defaults to 0.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter
    def prompt(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        """
        return pulumi.get(self, "prompt")

    @prompt.setter
    def prompt(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "prompt", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "settings", value)

    @_builtins.property
    @pulumi.getter
    def socket(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unix socket path to the hook process. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "socket")

    @socket.setter
    def socket(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "socket", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMs")
    def timeout_ms(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Per-call timeout in milliseconds. Defaults to 1.
        """
        return pulumi.get(self, "timeout_ms")

    @timeout_ms.setter
    def timeout_ms(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "timeout_ms", value)

    @_builtins.property
    @pulumi.getter
    def user(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user", value)

    @_builtins.property
    @pulumi.getter
    def webhook(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Webhook URL for the hook. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "webhook")

    @webhook.setter
    def webhook(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "webhook", value)


@pulumi.input_type
class _HookState:
    def __init__(__self__, *,
                 at: pulumi.Input[Optional[_builtins.str]] = None,
                 default: pulumi.Input[Optional[_builtins.bool]] = None,
                 global_: pulumi.Input[Optional[_builtins.bool]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_empty: pulumi.Input[Optional[_builtins.str]] = None,
                 on_error: pulumi.Input[Optional[_builtins.str]] = None,
                 priority: pulumi.Input[Optional[_builtins.int]] = None,
                 prompt: pulumi.Input[Optional[_builtins.str]] = None,
                 settings: pulumi.Input[Optional[_builtins.str]] = None,
                 socket: pulumi.Input[Optional[_builtins.str]] = None,
                 timeout_ms: pulumi.Input[Optional[_builtins.int]] = None,
                 user: pulumi.Input[Optional[_builtins.str]] = None,
                 webhook: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Hook resources.

        :param pulumi.Input[_builtins.str] at: Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        :param pulumi.Input[_builtins.bool] default: Whether this hook is the default for its stage. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.bool] global_: Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        :param pulumi.Input[_builtins.str] kind: Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] name: Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] on_empty: Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.str] on_error: Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        :param pulumi.Input[_builtins.int] priority: Ordering priority within a stage. Defaults to 0.
        :param pulumi.Input[_builtins.str] prompt: Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        :param pulumi.Input[_builtins.str] settings: Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        :param pulumi.Input[_builtins.str] socket: Unix socket path to the hook process. Exactly one of socket or webhook.
        :param pulumi.Input[_builtins.int] timeout_ms: Per-call timeout in milliseconds. Defaults to 1.
        :param pulumi.Input[_builtins.str] user: Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] webhook: Webhook URL for the hook. Exactly one of socket or webhook.
        """
        if at is not None:
            pulumi.set(__self__, "at", at)
        if default is not None:
            pulumi.set(__self__, "default", default)
        if global_ is not None:
            pulumi.set(__self__, "global_", global_)
        if kind is not None:
            pulumi.set(__self__, "kind", kind)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if on_empty is not None:
            pulumi.set(__self__, "on_empty", on_empty)
        if on_error is not None:
            pulumi.set(__self__, "on_error", on_error)
        if priority is not None:
            pulumi.set(__self__, "priority", priority)
        if prompt is not None:
            pulumi.set(__self__, "prompt", prompt)
        if settings is not None:
            pulumi.set(__self__, "settings", settings)
        if socket is not None:
            pulumi.set(__self__, "socket", socket)
        if timeout_ms is not None:
            pulumi.set(__self__, "timeout_ms", timeout_ms)
        if user is not None:
            pulumi.set(__self__, "user", user)
        if webhook is not None:
            pulumi.set(__self__, "webhook", webhook)

    @_builtins.property
    @pulumi.getter
    def at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        """
        return pulumi.get(self, "at")

    @at.setter
    def at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "at", value)

    @_builtins.property
    @pulumi.getter
    def default(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether this hook is the default for its stage. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "default")

    @default.setter
    def default(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "default", value)

    @_builtins.property
    @pulumi.getter(name="global")
    def global_(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        """
        return pulumi.get(self, "global_")

    @global_.setter
    def global_(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "global_", value)

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "kind")

    @kind.setter
    def kind(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kind", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="onEmpty")
    def on_empty(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "on_empty")

    @on_empty.setter
    def on_empty(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_empty", value)

    @_builtins.property
    @pulumi.getter(name="onError")
    def on_error(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        """
        return pulumi.get(self, "on_error")

    @on_error.setter
    def on_error(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "on_error", value)

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Ordering priority within a stage. Defaults to 0.
        """
        return pulumi.get(self, "priority")

    @priority.setter
    def priority(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "priority", value)

    @_builtins.property
    @pulumi.getter
    def prompt(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        """
        return pulumi.get(self, "prompt")

    @prompt.setter
    def prompt(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "prompt", value)

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        """
        return pulumi.get(self, "settings")

    @settings.setter
    def settings(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "settings", value)

    @_builtins.property
    @pulumi.getter
    def socket(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unix socket path to the hook process. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "socket")

    @socket.setter
    def socket(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "socket", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMs")
    def timeout_ms(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Per-call timeout in milliseconds. Defaults to 1.
        """
        return pulumi.get(self, "timeout_ms")

    @timeout_ms.setter
    def timeout_ms(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "timeout_ms", value)

    @_builtins.property
    @pulumi.getter
    def user(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "user")

    @user.setter
    def user(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user", value)

    @_builtins.property
    @pulumi.getter
    def webhook(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Webhook URL for the hook. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "webhook")

    @webhook.setter
    def webhook(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "webhook", value)


@pulumi.type_token("busbar:index/hook:Hook")
class Hook(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 at: pulumi.Input[Optional[_builtins.str]] = None,
                 default: pulumi.Input[Optional[_builtins.bool]] = None,
                 global_: pulumi.Input[Optional[_builtins.bool]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_empty: pulumi.Input[Optional[_builtins.str]] = None,
                 on_error: pulumi.Input[Optional[_builtins.str]] = None,
                 priority: pulumi.Input[Optional[_builtins.int]] = None,
                 prompt: pulumi.Input[Optional[_builtins.str]] = None,
                 settings: pulumi.Input[Optional[_builtins.str]] = None,
                 socket: pulumi.Input[Optional[_builtins.str]] = None,
                 timeout_ms: pulumi.Input[Optional[_builtins.int]] = None,
                 user: pulumi.Input[Optional[_builtins.str]] = None,
                 webhook: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Hook resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] at: Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        :param pulumi.Input[_builtins.bool] default: Whether this hook is the default for its stage. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.bool] global_: Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        :param pulumi.Input[_builtins.str] kind: Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] name: Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] on_empty: Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.str] on_error: Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        :param pulumi.Input[_builtins.int] priority: Ordering priority within a stage. Defaults to 0.
        :param pulumi.Input[_builtins.str] prompt: Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        :param pulumi.Input[_builtins.str] settings: Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        :param pulumi.Input[_builtins.str] socket: Unix socket path to the hook process. Exactly one of socket or webhook.
        :param pulumi.Input[_builtins.int] timeout_ms: Per-call timeout in milliseconds. Defaults to 1.
        :param pulumi.Input[_builtins.str] user: Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] webhook: Webhook URL for the hook. Exactly one of socket or webhook.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: HookArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Hook resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param HookArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(HookArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 at: pulumi.Input[Optional[_builtins.str]] = None,
                 default: pulumi.Input[Optional[_builtins.bool]] = None,
                 global_: pulumi.Input[Optional[_builtins.bool]] = None,
                 kind: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 on_empty: pulumi.Input[Optional[_builtins.str]] = None,
                 on_error: pulumi.Input[Optional[_builtins.str]] = None,
                 priority: pulumi.Input[Optional[_builtins.int]] = None,
                 prompt: pulumi.Input[Optional[_builtins.str]] = None,
                 settings: pulumi.Input[Optional[_builtins.str]] = None,
                 socket: pulumi.Input[Optional[_builtins.str]] = None,
                 timeout_ms: pulumi.Input[Optional[_builtins.int]] = None,
                 user: pulumi.Input[Optional[_builtins.str]] = None,
                 webhook: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = HookArgs.__new__(HookArgs)

            __props__.__dict__["at"] = at
            __props__.__dict__["default"] = default
            __props__.__dict__["global_"] = global_
            if kind is None and not opts.urn:
                raise TypeError("Missing required property 'kind'")
            __props__.__dict__["kind"] = kind
            __props__.__dict__["name"] = name
            __props__.__dict__["on_empty"] = on_empty
            __props__.__dict__["on_error"] = on_error
            __props__.__dict__["priority"] = priority
            __props__.__dict__["prompt"] = prompt
            __props__.__dict__["settings"] = settings
            __props__.__dict__["socket"] = socket
            __props__.__dict__["timeout_ms"] = timeout_ms
            __props__.__dict__["user"] = user
            __props__.__dict__["webhook"] = webhook
        super(Hook, __self__).__init__(
            'busbar:index/hook:Hook',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            at: pulumi.Input[Optional[_builtins.str]] = None,
            default: pulumi.Input[Optional[_builtins.bool]] = None,
            global_: pulumi.Input[Optional[_builtins.bool]] = None,
            kind: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            on_empty: pulumi.Input[Optional[_builtins.str]] = None,
            on_error: pulumi.Input[Optional[_builtins.str]] = None,
            priority: pulumi.Input[Optional[_builtins.int]] = None,
            prompt: pulumi.Input[Optional[_builtins.str]] = None,
            settings: pulumi.Input[Optional[_builtins.str]] = None,
            socket: pulumi.Input[Optional[_builtins.str]] = None,
            timeout_ms: pulumi.Input[Optional[_builtins.int]] = None,
            user: pulumi.Input[Optional[_builtins.str]] = None,
            webhook: pulumi.Input[Optional[_builtins.str]] = None) -> 'Hook':
        """
        Get an existing Hook resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] at: Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        :param pulumi.Input[_builtins.bool] default: Whether this hook is the default for its stage. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.bool] global_: Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        :param pulumi.Input[_builtins.str] kind: Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] name: Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] on_empty: Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        :param pulumi.Input[_builtins.str] on_error: Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        :param pulumi.Input[_builtins.int] priority: Ordering priority within a stage. Defaults to 0.
        :param pulumi.Input[_builtins.str] prompt: Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        :param pulumi.Input[_builtins.str] settings: Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        :param pulumi.Input[_builtins.str] socket: Unix socket path to the hook process. Exactly one of socket or webhook.
        :param pulumi.Input[_builtins.int] timeout_ms: Per-call timeout in milliseconds. Defaults to 1.
        :param pulumi.Input[_builtins.str] user: Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        :param pulumi.Input[_builtins.str] webhook: Webhook URL for the hook. Exactly one of socket or webhook.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _HookState.__new__(_HookState)

        __props__.__dict__["at"] = at
        __props__.__dict__["default"] = default
        __props__.__dict__["global_"] = global_
        __props__.__dict__["kind"] = kind
        __props__.__dict__["name"] = name
        __props__.__dict__["on_empty"] = on_empty
        __props__.__dict__["on_error"] = on_error
        __props__.__dict__["priority"] = priority
        __props__.__dict__["prompt"] = prompt
        __props__.__dict__["settings"] = settings
        __props__.__dict__["socket"] = socket
        __props__.__dict__["timeout_ms"] = timeout_ms
        __props__.__dict__["user"] = user
        __props__.__dict__["webhook"] = webhook
        return Hook(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def at(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
        """
        return pulumi.get(self, "at")

    @_builtins.property
    @pulumi.getter
    def default(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether this hook is the default for its stage. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "default")

    @_builtins.property
    @pulumi.getter(name="global")
    def global_(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
        """
        return pulumi.get(self, "global_")

    @_builtins.property
    @pulumi.getter
    def kind(self) -> pulumi.Output[_builtins.str]:
        """
        Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "kind")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="onEmpty")
    def on_empty(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
        """
        return pulumi.get(self, "on_empty")

    @_builtins.property
    @pulumi.getter(name="onError")
    def on_error(self) -> pulumi.Output[_builtins.str]:
        """
        Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
        """
        return pulumi.get(self, "on_error")

    @_builtins.property
    @pulumi.getter
    def priority(self) -> pulumi.Output[_builtins.int]:
        """
        Ordering priority within a stage. Defaults to 0.
        """
        return pulumi.get(self, "priority")

    @_builtins.property
    @pulumi.getter
    def prompt(self) -> pulumi.Output[_builtins.str]:
        """
        Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
        """
        return pulumi.get(self, "prompt")

    @_builtins.property
    @pulumi.getter
    def settings(self) -> pulumi.Output[_builtins.str]:
        """
        Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
        """
        return pulumi.get(self, "settings")

    @_builtins.property
    @pulumi.getter
    def socket(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Unix socket path to the hook process. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "socket")

    @_builtins.property
    @pulumi.getter(name="timeoutMs")
    def timeout_ms(self) -> pulumi.Output[_builtins.int]:
        """
        Per-call timeout in milliseconds. Defaults to 1.
        """
        return pulumi.get(self, "timeout_ms")

    @_builtins.property
    @pulumi.getter
    def user(self) -> pulumi.Output[_builtins.str]:
        """
        Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
        """
        return pulumi.get(self, "user")

    @_builtins.property
    @pulumi.getter
    def webhook(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Webhook URL for the hook. Exactly one of socket or webhook.
        """
        return pulumi.get(self, "webhook")

