# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VirtualKeyArgs', 'VirtualKey']

@pulumi.input_type
class VirtualKeyArgs:
    def __init__(__self__, *,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.int]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a VirtualKey resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        :param pulumi.Input[_builtins.int] expires_at: Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        :param pulumi.Input[_builtins.str] expires_in: Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        :param pulumi.Input[_builtins.str] group: The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] parent: Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        """
        if allowed_pools is not None:
            pulumi.set(__self__, "allowed_pools", allowed_pools)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if expires_in is not None:
            pulumi.set(__self__, "expires_in", expires_in)
        if group is not None:
            pulumi.set(__self__, "group", group)
        if issue_aws_credential is not None:
            pulumi.set(__self__, "issue_aws_credential", issue_aws_credential)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent is not None:
            pulumi.set(__self__, "parent", parent)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "allowed_pools")

    @allowed_pools.setter
    def allowed_pools(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_pools", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        """
        return pulumi.get(self, "expires_in")

    @expires_in.setter
    def expires_in(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_in", value)

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        """
        return pulumi.get(self, "group")

    @group.setter
    def group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group", value)

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @issue_aws_credential.setter
    def issue_aws_credential(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "issue_aws_credential", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def parent(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        """
        return pulumi.get(self, "parent")

    @parent.setter
    def parent(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent", value)


@pulumi.input_type
class _VirtualKeyState:
    def __init__(__self__, *,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 aws_access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 aws_secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.int]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.int]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 group_provisioned: pulumi.Input[Optional[_builtins.bool]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent: pulumi.Input[Optional[_builtins.str]] = None,
                 state: pulumi.Input[Optional[_builtins.str]] = None,
                 token: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering VirtualKey resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] aws_access_key_id: AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
        :param pulumi.Input[_builtins.str] aws_secret_access_key: AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.int] created_at: Epoch seconds the key was minted.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        :param pulumi.Input[_builtins.int] expires_at: Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        :param pulumi.Input[_builtins.str] expires_in: Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        :param pulumi.Input[_builtins.str] group: The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        :param pulumi.Input[_builtins.bool] group_provisioned: Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] parent: Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        :param pulumi.Input[_builtins.str] state: Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
        :param pulumi.Input[_builtins.str] token: The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
        """
        if allowed_pools is not None:
            pulumi.set(__self__, "allowed_pools", allowed_pools)
        if aws_access_key_id is not None:
            pulumi.set(__self__, "aws_access_key_id", aws_access_key_id)
        if aws_secret_access_key is not None:
            pulumi.set(__self__, "aws_secret_access_key", aws_secret_access_key)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if expires_in is not None:
            pulumi.set(__self__, "expires_in", expires_in)
        if group is not None:
            pulumi.set(__self__, "group", group)
        if group_provisioned is not None:
            pulumi.set(__self__, "group_provisioned", group_provisioned)
        if issue_aws_credential is not None:
            pulumi.set(__self__, "issue_aws_credential", issue_aws_credential)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if parent is not None:
            pulumi.set(__self__, "parent", parent)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "allowed_pools")

    @allowed_pools.setter
    def allowed_pools(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_pools", value)

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
        """
        return pulumi.get(self, "aws_access_key_id")

    @aws_access_key_id.setter
    def aws_access_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "aws_access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "aws_secret_access_key")

    @aws_secret_access_key.setter
    def aws_secret_access_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "aws_secret_access_key", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Epoch seconds the key was minted.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        """
        return pulumi.get(self, "expires_in")

    @expires_in.setter
    def expires_in(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_in", value)

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        """
        return pulumi.get(self, "group")

    @group.setter
    def group(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "group", value)

    @_builtins.property
    @pulumi.getter(name="groupProvisioned")
    def group_provisioned(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
        """
        return pulumi.get(self, "group_provisioned")

    @group_provisioned.setter
    def group_provisioned(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "group_provisioned", value)

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @issue_aws_credential.setter
    def issue_aws_credential(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "issue_aws_credential", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def parent(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        """
        return pulumi.get(self, "parent")

    @parent.setter
    def parent(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("busbar:index/virtualKey:VirtualKey")
class VirtualKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.int]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A governance virtual key (busbar >= 1.5.0): a mintable, revocable, EXPIRING signed-token credential, optionally bound to a `groups:` bucket that carries all budget and rate enforcement (POST/GET/PATCH/DELETE /api/v1/admin/keys). The signed token is returned by busbar only once, at creation, and is stored in state as a sensitive value; refreshes update metadata (group/enabled/state) but never the token. Requires governance to be enabled on the gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_busbar as busbar

        # Mint a governance virtual key (busbar >= 1.5.0): a signed, expiring token,
        # bound to a `groups:` bucket that carries all budget/rate enforcement, scoped
        # to the "smart" pool. The signed token is returned only once, at creation, and
        # stored in state as a sensitive value.
        app = busbar.VirtualKey("app",
            name="checkout-service",
            group="team-checkout",
            allowed_pools=["smart"],
            expires_in="30d",
            labels={
                "service": "checkout",
            })
        pulumi.export("appKeyToken", app.token)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Virtual keys are imported by their server-assigned id (the signed token
        cannot be recovered — it is create-only — and stays null after import).

        ```sh
        $ pulumi import busbar:index/virtualKey:VirtualKey app vk_0123456789abcdef
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        :param pulumi.Input[_builtins.int] expires_at: Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        :param pulumi.Input[_builtins.str] expires_in: Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        :param pulumi.Input[_builtins.str] group: The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] parent: Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[VirtualKeyArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A governance virtual key (busbar >= 1.5.0): a mintable, revocable, EXPIRING signed-token credential, optionally bound to a `groups:` bucket that carries all budget and rate enforcement (POST/GET/PATCH/DELETE /api/v1/admin/keys). The signed token is returned by busbar only once, at creation, and is stored in state as a sensitive value; refreshes update metadata (group/enabled/state) but never the token. Requires governance to be enabled on the gateway.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_busbar as busbar

        # Mint a governance virtual key (busbar >= 1.5.0): a signed, expiring token,
        # bound to a `groups:` bucket that carries all budget/rate enforcement, scoped
        # to the "smart" pool. The signed token is returned only once, at creation, and
        # stored in state as a sensitive value.
        app = busbar.VirtualKey("app",
            name="checkout-service",
            group="team-checkout",
            allowed_pools=["smart"],
            expires_in="30d",
            labels={
                "service": "checkout",
            })
        pulumi.export("appKeyToken", app.token)
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Virtual keys are imported by their server-assigned id (the signed token
        cannot be recovered — it is create-only — and stays null after import).

        ```sh
        $ pulumi import busbar:index/virtualKey:VirtualKey app vk_0123456789abcdef
        ```


        :param str resource_name: The name of the resource.
        :param VirtualKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VirtualKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.int]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 group: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VirtualKeyArgs.__new__(VirtualKeyArgs)

            __props__.__dict__["allowed_pools"] = allowed_pools
            __props__.__dict__["enabled"] = enabled
            __props__.__dict__["expires_at"] = expires_at
            __props__.__dict__["expires_in"] = expires_in
            __props__.__dict__["group"] = group
            __props__.__dict__["issue_aws_credential"] = issue_aws_credential
            __props__.__dict__["labels"] = labels
            __props__.__dict__["name"] = name
            __props__.__dict__["parent"] = parent
            __props__.__dict__["aws_access_key_id"] = None
            __props__.__dict__["aws_secret_access_key"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["group_provisioned"] = None
            __props__.__dict__["state"] = None
            __props__.__dict__["token"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["awsSecretAccessKey", "token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(VirtualKey, __self__).__init__(
            'busbar:index/virtualKey:VirtualKey',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            aws_access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
            aws_secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.int]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            expires_at: pulumi.Input[Optional[_builtins.int]] = None,
            expires_in: pulumi.Input[Optional[_builtins.str]] = None,
            group: pulumi.Input[Optional[_builtins.str]] = None,
            group_provisioned: pulumi.Input[Optional[_builtins.bool]] = None,
            issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            parent: pulumi.Input[Optional[_builtins.str]] = None,
            state: pulumi.Input[Optional[_builtins.str]] = None,
            token: pulumi.Input[Optional[_builtins.str]] = None) -> 'VirtualKey':
        """
        Get an existing VirtualKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] aws_access_key_id: AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
        :param pulumi.Input[_builtins.str] aws_secret_access_key: AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.int] created_at: Epoch seconds the key was minted.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        :param pulumi.Input[_builtins.int] expires_at: Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        :param pulumi.Input[_builtins.str] expires_in: Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        :param pulumi.Input[_builtins.str] group: The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        :param pulumi.Input[_builtins.bool] group_provisioned: Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.str] parent: Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        :param pulumi.Input[_builtins.str] state: Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
        :param pulumi.Input[_builtins.str] token: The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VirtualKeyState.__new__(_VirtualKeyState)

        __props__.__dict__["allowed_pools"] = allowed_pools
        __props__.__dict__["aws_access_key_id"] = aws_access_key_id
        __props__.__dict__["aws_secret_access_key"] = aws_secret_access_key
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["expires_at"] = expires_at
        __props__.__dict__["expires_in"] = expires_in
        __props__.__dict__["group"] = group
        __props__.__dict__["group_provisioned"] = group_provisioned
        __props__.__dict__["issue_aws_credential"] = issue_aws_credential
        __props__.__dict__["labels"] = labels
        __props__.__dict__["name"] = name
        __props__.__dict__["parent"] = parent
        __props__.__dict__["state"] = state
        __props__.__dict__["token"] = token
        return VirtualKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "allowed_pools")

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
        """
        return pulumi.get(self, "aws_access_key_id")

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> pulumi.Output[_builtins.str]:
        """
        AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "aws_secret_access_key")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.int]:
        """
        Epoch seconds the key was minted.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[_builtins.int]:
        """
        Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expires_in`) and is always computed from the mint response. Changing it replaces the key.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expires_at`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
        """
        return pulumi.get(self, "expires_in")

    @_builtins.property
    @pulumi.getter
    def group(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
        """
        return pulumi.get(self, "group")

    @_builtins.property
    @pulumi.getter(name="groupProvisioned")
    def group_provisioned(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
        """
        return pulumi.get(self, "group_provisioned")

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def parent(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
        """
        return pulumi.get(self, "parent")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[_builtins.str]:
        """
        Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[_builtins.str]:
        """
        The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "token")

