# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VirtualKeyArgs', 'VirtualKey']

@pulumi.input_type
class VirtualKeyArgs:
    def __init__(__self__, *,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 budget_period: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 max_budget_cents: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 tpm_limit: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a VirtualKey resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        :param pulumi.Input[_builtins.str] budget_period: Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[_builtins.int] max_budget_cents: Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] rpm_limit: Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.int] tpm_limit: Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        if allowed_pools is not None:
            pulumi.set(__self__, "allowed_pools", allowed_pools)
        if budget_period is not None:
            pulumi.set(__self__, "budget_period", budget_period)
        if issue_aws_credential is not None:
            pulumi.set(__self__, "issue_aws_credential", issue_aws_credential)
        if max_budget_cents is not None:
            pulumi.set(__self__, "max_budget_cents", max_budget_cents)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rpm_limit is not None:
            pulumi.set(__self__, "rpm_limit", rpm_limit)
        if tpm_limit is not None:
            pulumi.set(__self__, "tpm_limit", tpm_limit)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        """
        return pulumi.get(self, "allowed_pools")

    @allowed_pools.setter
    def allowed_pools(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_pools", value)

    @_builtins.property
    @pulumi.getter(name="budgetPeriod")
    def budget_period(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "budget_period")

    @budget_period.setter
    def budget_period(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "budget_period", value)

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @issue_aws_credential.setter
    def issue_aws_credential(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "issue_aws_credential", value)

    @_builtins.property
    @pulumi.getter(name="maxBudgetCents")
    def max_budget_cents(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "max_budget_cents")

    @max_budget_cents.setter
    def max_budget_cents(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_budget_cents", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rpmLimit")
    def rpm_limit(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "rpm_limit")

    @rpm_limit.setter
    def rpm_limit(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "rpm_limit", value)

    @_builtins.property
    @pulumi.getter(name="tpmLimit")
    def tpm_limit(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "tpm_limit")

    @tpm_limit.setter
    def tpm_limit(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "tpm_limit", value)


@pulumi.input_type
class _VirtualKeyState:
    def __init__(__self__, *,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 aws_access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
                 aws_secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
                 budget_period: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.int]] = None,
                 enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 max_budget_cents: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 secret: pulumi.Input[Optional[_builtins.str]] = None,
                 tpm_limit: pulumi.Input[Optional[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering VirtualKey resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        :param pulumi.Input[_builtins.str] aws_access_key_id: AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
        :param pulumi.Input[_builtins.str] aws_secret_access_key: AWS-style secret access key, when issue_aws_credential is true. Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.str] budget_period: Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] created_at: Epoch seconds the key was minted.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[_builtins.int] max_budget_cents: Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] rpm_limit: Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] secret: The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.int] tpm_limit: Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        if allowed_pools is not None:
            pulumi.set(__self__, "allowed_pools", allowed_pools)
        if aws_access_key_id is not None:
            pulumi.set(__self__, "aws_access_key_id", aws_access_key_id)
        if aws_secret_access_key is not None:
            pulumi.set(__self__, "aws_secret_access_key", aws_secret_access_key)
        if budget_period is not None:
            pulumi.set(__self__, "budget_period", budget_period)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if issue_aws_credential is not None:
            pulumi.set(__self__, "issue_aws_credential", issue_aws_credential)
        if max_budget_cents is not None:
            pulumi.set(__self__, "max_budget_cents", max_budget_cents)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if rpm_limit is not None:
            pulumi.set(__self__, "rpm_limit", rpm_limit)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if tpm_limit is not None:
            pulumi.set(__self__, "tpm_limit", tpm_limit)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        """
        return pulumi.get(self, "allowed_pools")

    @allowed_pools.setter
    def allowed_pools(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_pools", value)

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
        """
        return pulumi.get(self, "aws_access_key_id")

    @aws_access_key_id.setter
    def aws_access_key_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "aws_access_key_id", value)

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        AWS-style secret access key, when issue_aws_credential is true. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "aws_secret_access_key")

    @aws_secret_access_key.setter
    def aws_secret_access_key(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "aws_secret_access_key", value)

    @_builtins.property
    @pulumi.getter(name="budgetPeriod")
    def budget_period(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "budget_period")

    @budget_period.setter
    def budget_period(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "budget_period", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Epoch seconds the key was minted.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @issue_aws_credential.setter
    def issue_aws_credential(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "issue_aws_credential", value)

    @_builtins.property
    @pulumi.getter(name="maxBudgetCents")
    def max_budget_cents(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "max_budget_cents")

    @max_budget_cents.setter
    def max_budget_cents(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "max_budget_cents", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="rpmLimit")
    def rpm_limit(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "rpm_limit")

    @rpm_limit.setter
    def rpm_limit(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "rpm_limit", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter(name="tpmLimit")
    def tpm_limit(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "tpm_limit")

    @tpm_limit.setter
    def tpm_limit(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "tpm_limit", value)


@pulumi.type_token("busbar:index/virtualKey:VirtualKey")
class VirtualKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 budget_period: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 max_budget_cents: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 tpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Create a VirtualKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        :param pulumi.Input[_builtins.str] budget_period: Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[_builtins.int] max_budget_cents: Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] rpm_limit: Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.int] tpm_limit: Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[VirtualKeyArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VirtualKey resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param VirtualKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VirtualKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 budget_period: pulumi.Input[Optional[_builtins.str]] = None,
                 issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
                 max_budget_cents: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 rpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 tpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VirtualKeyArgs.__new__(VirtualKeyArgs)

            __props__.__dict__["allowed_pools"] = allowed_pools
            __props__.__dict__["budget_period"] = budget_period
            __props__.__dict__["issue_aws_credential"] = issue_aws_credential
            __props__.__dict__["max_budget_cents"] = max_budget_cents
            __props__.__dict__["name"] = name
            __props__.__dict__["rpm_limit"] = rpm_limit
            __props__.__dict__["tpm_limit"] = tpm_limit
            __props__.__dict__["aws_access_key_id"] = None
            __props__.__dict__["aws_secret_access_key"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["enabled"] = None
            __props__.__dict__["secret"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["awsSecretAccessKey", "secret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(VirtualKey, __self__).__init__(
            'busbar:index/virtualKey:VirtualKey',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allowed_pools: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            aws_access_key_id: pulumi.Input[Optional[_builtins.str]] = None,
            aws_secret_access_key: pulumi.Input[Optional[_builtins.str]] = None,
            budget_period: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.int]] = None,
            enabled: pulumi.Input[Optional[_builtins.bool]] = None,
            issue_aws_credential: pulumi.Input[Optional[_builtins.bool]] = None,
            max_budget_cents: pulumi.Input[Optional[_builtins.int]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            rpm_limit: pulumi.Input[Optional[_builtins.int]] = None,
            secret: pulumi.Input[Optional[_builtins.str]] = None,
            tpm_limit: pulumi.Input[Optional[_builtins.int]] = None) -> 'VirtualKey':
        """
        Get an existing VirtualKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_pools: Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        :param pulumi.Input[_builtins.str] aws_access_key_id: AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
        :param pulumi.Input[_builtins.str] aws_secret_access_key: AWS-style secret access key, when issue_aws_credential is true. Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.str] budget_period: Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] created_at: Epoch seconds the key was minted.
        :param pulumi.Input[_builtins.bool] enabled: Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
        :param pulumi.Input[_builtins.bool] issue_aws_credential: When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        :param pulumi.Input[_builtins.int] max_budget_cents: Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] name: Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        :param pulumi.Input[_builtins.int] rpm_limit: Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        :param pulumi.Input[_builtins.str] secret: The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
        :param pulumi.Input[_builtins.int] tpm_limit: Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _VirtualKeyState.__new__(_VirtualKeyState)

        __props__.__dict__["allowed_pools"] = allowed_pools
        __props__.__dict__["aws_access_key_id"] = aws_access_key_id
        __props__.__dict__["aws_secret_access_key"] = aws_secret_access_key
        __props__.__dict__["budget_period"] = budget_period
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["issue_aws_credential"] = issue_aws_credential
        __props__.__dict__["max_budget_cents"] = max_budget_cents
        __props__.__dict__["name"] = name
        __props__.__dict__["rpm_limit"] = rpm_limit
        __props__.__dict__["secret"] = secret
        __props__.__dict__["tpm_limit"] = tpm_limit
        return VirtualKey(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowedPools")
    def allowed_pools(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
        """
        return pulumi.get(self, "allowed_pools")

    @_builtins.property
    @pulumi.getter(name="awsAccessKeyId")
    def aws_access_key_id(self) -> pulumi.Output[_builtins.str]:
        """
        AWS-style access key id, when issue_aws_credential is true. Returned only at creation.
        """
        return pulumi.get(self, "aws_access_key_id")

    @_builtins.property
    @pulumi.getter(name="awsSecretAccessKey")
    def aws_secret_access_key(self) -> pulumi.Output[_builtins.str]:
        """
        AWS-style secret access key, when issue_aws_credential is true. Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "aws_secret_access_key")

    @_builtins.property
    @pulumi.getter(name="budgetPeriod")
    def budget_period(self) -> pulumi.Output[_builtins.str]:
        """
        Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "budget_period")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.int]:
        """
        Epoch seconds the key was minted.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="issueAwsCredential")
    def issue_aws_credential(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
        """
        return pulumi.get(self, "issue_aws_credential")

    @_builtins.property
    @pulumi.getter(name="maxBudgetCents")
    def max_budget_cents(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "max_budget_cents")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="rpmLimit")
    def rpm_limit(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "rpm_limit")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[_builtins.str]:
        """
        The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter(name="tpmLimit")
    def tpm_limit(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
        """
        return pulumi.get(self, "tpm_limit")

