# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

caCertPem: Optional[str]
"""
PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
"""

clientCertPem: Optional[str]
"""
PEM-encoded client certificate for mTLS against a cert-gated admin plane.
"""

clientKeyPem: Optional[str]
"""
PEM-encoded private key for client_cert_pem.
"""

endpoint: Optional[str]
"""
Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
"""

insecure: Optional[bool]
"""
Skip TLS certificate verification. Development only; never use against production.
"""

token: Optional[str]
"""
Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
"""

