# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('busbar')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def ca_cert_pem(self) -> Optional[str]:
        """
        PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
        """
        return __config__.get('caCertPem')

    @_builtins.property
    def client_cert_pem(self) -> Optional[str]:
        """
        PEM-encoded client certificate for mTLS against a cert-gated admin plane.
        """
        return __config__.get('clientCertPem')

    @_builtins.property
    def client_key_pem(self) -> Optional[str]:
        """
        PEM-encoded private key for client_cert_pem.
        """
        return __config__.get('clientKeyPem')

    @_builtins.property
    def endpoint(self) -> Optional[str]:
        """
        Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
        """
        return __config__.get('endpoint') or _utilities.get_env('BUSBAR_ENDPOINT')

    @_builtins.property
    def insecure(self) -> Optional[bool]:
        """
        Skip TLS certificate verification. Development only; never use against production.
        """
        return __config__.get_bool('insecure')

    @_builtins.property
    def token(self) -> Optional[str]:
        """
        Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
        """
        return __config__.get('token') or _utilities.get_env('BUSBAR_ADMIN_TOKEN')

