// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A GitOps singleton that owns the running busbar config and applies it wholesale (POST /api/v1/admin/config/apply). Manage at most ONE of these per gateway. The document is the full JSON config payload busbar boots from ({"config": {...}, "providers": {...}}); applying it bumps config_version. Applies are LIVE-ONLY by default — they revert to disk truth on the next reload or restart unless the gateway persists an overlay. Destroying this resource is a no-op on the gateway (there is no unapply); it only drops Terraform's tracking.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as busbar from "@getbusbar/pulumi-busbar";
 *
 * // GitOps singleton: apply the whole running config document. Manage AT MOST ONE
 * // busbar_config per gateway. The document is the JSON payload busbar boots from,
 * // an envelope of { config = {DeployCfg}, providers = {name = ProviderDef} }.
 * //
 * // Applies are live-only by default: they revert to disk truth on the next reload
 * // or restart unless the gateway persists an overlay. Destroying this resource is a
 * // no-op on the gateway (there is no "unapply"); it only drops Terraform's tracking.
 * const running = new busbar.Config("running", {document: JSON.stringify({
 *     config: {
 *         auth: null,
 *         models: {
 *             "claude-sonnet": {
 *                 provider: "anthropic",
 *                 max_concurrent: 8,
 *                 max_requests: -1,
 *             },
 *         },
 *         providers: {
 *             anthropic: {
 *                 api_key_env: "ANTHROPIC_API_KEY",
 *             },
 *         },
 *         governance: {
 *             enabled: true,
 *             db_path: "/var/lib/busbar/governance.db",
 *             admin_token: busbarAdminToken,
 *         },
 *     },
 *     providers: {
 *         anthropic: {
 *             protocol: "anthropic",
 *             base_url: "https://api.anthropic.com",
 *         },
 *     },
 * })});
 * export const configVersion = running.configVersion;
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * The config singleton has a fixed import id. The document is not recoverable
 * (GET /config is a redacted projection), so supply the matching `document` in
 * your configuration after import; only configVersion is read live.
 *
 * ```sh
 * $ pulumi import busbar:index/config:Config running config
 * ```
 */
export class Config extends pulumi.CustomResource {
    /**
     * Get an existing Config resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConfigState, opts?: pulumi.CustomResourceOptions): Config {
        return new Config(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'busbar:index/config:Config';

    /**
     * Returns true if the given object is an instance of Config.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Config {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Config.__pulumiType;
    }

    /**
     * The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
     */
    declare public /*out*/ readonly configVersion: pulumi.Output<number>;
    /**
     * The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
     */
    declare public readonly document: pulumi.Output<string>;

    /**
     * Create a Config resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConfigArgs | ConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConfigState | undefined;
            resourceInputs["configVersion"] = state?.configVersion;
            resourceInputs["document"] = state?.document;
        } else {
            const args = argsOrState as ConfigArgs | undefined;
            if (args?.document === undefined && !opts.urn) {
                throw new Error("Missing required property 'document'");
            }
            resourceInputs["document"] = args?.document;
            resourceInputs["configVersion"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Config.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Config resources.
 */
export interface ConfigState {
    /**
     * The monotonic config version after the last apply. Process-local; resets to 0 on gateway restart.
     */
    configVersion?: pulumi.Input<number | undefined>;
    /**
     * The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
     */
    document?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Config resource.
 */
export interface ConfigArgs {
    /**
     * The full config apply document as a JSON string: {"config": {DeployCfg}, "providers": {name: ProviderDef}}. The `config` key is required; `providers` is optional. This is the write model (the boot-file shape), NOT the redacted read projection returned by GET /config.
     */
    document: pulumi.Input<string>;
}
