// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getInfo(opts?: pulumi.InvokeOptions): Promise<GetInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("busbar:index/getInfo:getInfo", {
    }, opts);
}

/**
 * A collection of values returned by getInfo.
 */
export interface GetInfoResult {
    readonly authModules: string[];
    readonly configPersistence: boolean;
    readonly configVersion: number;
    readonly hookPlugins: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly models: number;
    readonly pools: number;
    readonly providers: number;
    readonly startedAt: number;
    readonly uptimeSeconds: number;
    readonly version: string;
    readonly weightedFloor: boolean;
}
export function getInfoOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("busbar:index/getInfo:getInfo", {
    }, opts);
}
