// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A routing hook (busbar >= 1.5.0): a tap or gate backed by a signed `kind: hook` plugin, wired into busbar's request/ranking pipeline (POST/GET/PUT/DELETE /api/v1/admin/hooks). The grant fields (kind, prompt, user) are immutable once registered — changing them replaces the hook.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as busbar from "@getbusbar/pulumi-busbar";
 *
 * // Register a blocking "gate" hook backed by a signed `kind: hook` plugin from
 * // the gateway's plugin catalog: it may inspect (prompt = "ro") and rerank
 * // candidates before the request is dispatched.
 * const ranker = new busbar.Hook("ranker", {
 *     name: "quality-ranker",
 *     kind: "gate",
 *     plugin: "ranking",
 *     prompt: "ro",
 *     timeoutMs: 100,
 *     priority: 10,
 *     onError: "weighted",
 *     settings: JSON.stringify({
 *         min_score: 0.6,
 *     }),
 * });
 * // A fire-and-forget "tap" hook for async usage telemetry.
 * const usageTap = new busbar.Hook("usage_tap", {
 *     name: "usage-telemetry",
 *     kind: "tap",
 *     plugin: "usage-telemetry",
 *     at: "completion",
 *     global: true,
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Hooks are imported by name.
 *
 * ```sh
 * $ pulumi import busbar:index/hook:Hook ranker quality-ranker
 * ```
 */
export class Hook extends pulumi.CustomResource {
    /**
     * Get an existing Hook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: HookState, opts?: pulumi.CustomResourceOptions): Hook {
        return new Hook(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'busbar:index/hook:Hook';

    /**
     * Returns true if the given object is an instance of Hook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Hook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Hook.__pulumiType;
    }

    /**
     * Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
     */
    declare public readonly at: pulumi.Output<string | undefined>;
    /**
     * Whether this hook is the default for its stage. Write-only (not echoed by reads).
     */
    declare public readonly default: pulumi.Output<boolean | undefined>;
    /**
     * Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
     */
    declare public readonly global: pulumi.Output<boolean>;
    /**
     * Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
     */
    declare public readonly kind: pulumi.Output<string>;
    /**
     * Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
     */
    declare public readonly onEmpty: pulumi.Output<string | undefined>;
    /**
     * Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
     */
    declare public readonly onError: pulumi.Output<string>;
    /**
     * The signed `kind: hook` plugin this hook dispatches to (its NAME from the gateway's plugin catalog, e.g. a compiled-in plugin such as `ranking`).
     */
    declare public readonly plugin: pulumi.Output<string>;
    /**
     * Ordering priority within a stage. Defaults to 0.
     */
    declare public readonly priority: pulumi.Output<number>;
    /**
     * Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
     */
    declare public readonly prompt: pulumi.Output<string>;
    /**
     * Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
     */
    declare public readonly settings: pulumi.Output<string>;
    /**
     * Per-call timeout in milliseconds. Defaults to 1.
     */
    declare public readonly timeoutMs: pulumi.Output<number>;
    /**
     * Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
     */
    declare public readonly user: pulumi.Output<string>;

    /**
     * Create a Hook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: HookArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: HookArgs | HookState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as HookState | undefined;
            resourceInputs["at"] = state?.at;
            resourceInputs["default"] = state?.default;
            resourceInputs["global"] = state?.global;
            resourceInputs["kind"] = state?.kind;
            resourceInputs["name"] = state?.name;
            resourceInputs["onEmpty"] = state?.onEmpty;
            resourceInputs["onError"] = state?.onError;
            resourceInputs["plugin"] = state?.plugin;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["prompt"] = state?.prompt;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["timeoutMs"] = state?.timeoutMs;
            resourceInputs["user"] = state?.user;
        } else {
            const args = argsOrState as HookArgs | undefined;
            if (args?.kind === undefined && !opts.urn) {
                throw new Error("Missing required property 'kind'");
            }
            if (args?.plugin === undefined && !opts.urn) {
                throw new Error("Missing required property 'plugin'");
            }
            resourceInputs["at"] = args?.at;
            resourceInputs["default"] = args?.default;
            resourceInputs["global"] = args?.global;
            resourceInputs["kind"] = args?.kind;
            resourceInputs["name"] = args?.name;
            resourceInputs["onEmpty"] = args?.onEmpty;
            resourceInputs["onError"] = args?.onError;
            resourceInputs["plugin"] = args?.plugin;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["prompt"] = args?.prompt;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["timeoutMs"] = args?.timeoutMs;
            resourceInputs["user"] = args?.user;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Hook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Hook resources.
 */
export interface HookState {
    /**
     * Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
     */
    at?: pulumi.Input<string | undefined>;
    /**
     * Whether this hook is the default for its stage. Write-only (not echoed by reads).
     */
    default?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
     */
    global?: pulumi.Input<boolean | undefined>;
    /**
     * Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
     */
    kind?: pulumi.Input<string | undefined>;
    /**
     * Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
     */
    onEmpty?: pulumi.Input<string | undefined>;
    /**
     * Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
     */
    onError?: pulumi.Input<string | undefined>;
    /**
     * The signed `kind: hook` plugin this hook dispatches to (its NAME from the gateway's plugin catalog, e.g. a compiled-in plugin such as `ranking`).
     */
    plugin?: pulumi.Input<string | undefined>;
    /**
     * Ordering priority within a stage. Defaults to 0.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
     */
    prompt?: pulumi.Input<string | undefined>;
    /**
     * Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
     */
    settings?: pulumi.Input<string | undefined>;
    /**
     * Per-call timeout in milliseconds. Defaults to 1.
     */
    timeoutMs?: pulumi.Input<number | undefined>;
    /**
     * Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
     */
    user?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Hook resource.
 */
export interface HookArgs {
    /**
     * Pipeline stage: request, route, attempt, or completion. Null lets busbar place it by kind.
     */
    at?: pulumi.Input<string | undefined>;
    /**
     * Whether this hook is the default for its stage. Write-only (not echoed by reads).
     */
    default?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the hook applies globally (all pools). Defaults to false. May read back true if wired via global_hooks.
     */
    global?: pulumi.Input<boolean | undefined>;
    /**
     * Transport contract: tap (fire-and-forget, non-blocking) or gate (blocking, may rewrite/reject). Immutable grant; changing it replaces the hook.
     */
    kind: pulumi.Input<string>;
    /**
     * Unique hook name (<= 256 chars; not a reserved terminal name). Immutable; changing it replaces the hook.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Fallback policy when the hook yields an empty ranking: weighted, reject, or first. Write-only (not echoed by reads).
     */
    onEmpty?: pulumi.Input<string | undefined>;
    /**
     * Behavior when the hook errors/times out: a terminal (weighted, reject, first, nothing) or another hook name. Defaults to nothing.
     */
    onError?: pulumi.Input<string | undefined>;
    /**
     * The signed `kind: hook` plugin this hook dispatches to (its NAME from the gateway's plugin catalog, e.g. a compiled-in plugin such as `ranking`).
     */
    plugin: pulumi.Input<string>;
    /**
     * Ordering priority within a stage. Defaults to 0.
     */
    priority?: pulumi.Input<number | undefined>;
    /**
     * Prompt-content access grant: no, ro, or rw. Defaults to no. Immutable grant; changing it replaces the hook. (rw is invalid on a tap.)
     */
    prompt?: pulumi.Input<string | undefined>;
    /**
     * Opaque per-hook settings as a JSON object string (<= 64KiB, <= 256 keys). Defaults to {}.
     */
    settings?: pulumi.Input<string | undefined>;
    /**
     * Per-call timeout in milliseconds. Defaults to 1.
     */
    timeoutMs?: pulumi.Input<number | undefined>;
    /**
     * Caller-identity access grant: no or ro. Defaults to no. Immutable grant; changing it replaces the hook.
     */
    user?: pulumi.Input<string | undefined>;
}
