// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ConfigArgs, ConfigState } from "./config_";
export type Config = import("./config_").Config;
export const Config: typeof import("./config_").Config = null as any;
utilities.lazyLoad(exports, ["Config"], () => require("./config_"));

export { GetInfoResult } from "./getInfo";
export const getInfo: typeof import("./getInfo").getInfo = null as any;
export const getInfoOutput: typeof import("./getInfo").getInfoOutput = null as any;
utilities.lazyLoad(exports, ["getInfo","getInfoOutput"], () => require("./getInfo"));

export { HookArgs, HookState } from "./hook";
export type Hook = import("./hook").Hook;
export const Hook: typeof import("./hook").Hook = null as any;
utilities.lazyLoad(exports, ["Hook"], () => require("./hook"));

export * from "./provider";
import { Provider } from "./provider";

export { VirtualKeyArgs, VirtualKeyState } from "./virtualKey";
export type VirtualKey = import("./virtualKey").VirtualKey;
export const VirtualKey: typeof import("./virtualKey").VirtualKey = null as any;
utilities.lazyLoad(exports, ["VirtualKey"], () => require("./virtualKey"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "busbar:index/config:Config":
                return new Config(name, <any>undefined, { urn })
            case "busbar:index/hook:Hook":
                return new Hook(name, <any>undefined, { urn })
            case "busbar:index/virtualKey:VirtualKey":
                return new VirtualKey(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("busbar", "index/config", _module)
pulumi.runtime.registerResourceModule("busbar", "index/hook", _module)
pulumi.runtime.registerResourceModule("busbar", "index/virtualKey", _module)
pulumi.runtime.registerResourcePackage("busbar", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:busbar") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
