// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the busbar package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'busbar';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
     */
    declare public readonly caCertPem: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded client certificate for mTLS against a cert-gated admin plane.
     */
    declare public readonly clientCertPem: pulumi.Output<string | undefined>;
    /**
     * PEM-encoded private key for client_cert_pem.
     */
    declare public readonly clientKeyPem: pulumi.Output<string | undefined>;
    /**
     * Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
     */
    declare public readonly token: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["caCertPem"] = args?.caCertPem;
            resourceInputs["clientCertPem"] = args?.clientCertPem;
            resourceInputs["clientKeyPem"] = args?.clientKeyPem ? pulumi.secret(args.clientKeyPem) : undefined;
            resourceInputs["endpoint"] = (args?.endpoint) ?? utilities.getEnv("BUSBAR_ENDPOINT");
            resourceInputs["insecure"] = pulumi.output(args?.insecure).apply(JSON.stringify);
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? utilities.getEnv("BUSBAR_ADMIN_TOKEN");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientKeyPem", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:busbar/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * PEM-encoded CA certificate to trust the admin server's certificate (e.g. a private CA).
     */
    caCertPem?: pulumi.Input<string | undefined>;
    /**
     * PEM-encoded client certificate for mTLS against a cert-gated admin plane.
     */
    clientCertPem?: pulumi.Input<string | undefined>;
    /**
     * PEM-encoded private key for client_cert_pem.
     */
    clientKeyPem?: pulumi.Input<string | undefined>;
    /**
     * Admin listener URL, e.g. https://busbar-admin.internal:8081. May also be set with the BUSBAR_ENDPOINT environment variable.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * Skip TLS certificate verification. Development only; never use against production.
     */
    insecure?: pulumi.Input<boolean | undefined>;
    /**
     * Operator admin token, sent as the x-admin-token header. May also be set with the BUSBAR_ADMIN_TOKEN environment variable.
     */
    token?: pulumi.Input<string | undefined>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
