// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VirtualKey extends pulumi.CustomResource {
    /**
     * Get an existing VirtualKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VirtualKeyState, opts?: pulumi.CustomResourceOptions): VirtualKey {
        return new VirtualKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'busbar:index/virtualKey:VirtualKey';

    /**
     * Returns true if the given object is an instance of VirtualKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VirtualKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VirtualKey.__pulumiType;
    }

    /**
     * Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
     */
    declare public readonly allowedPools: pulumi.Output<string[] | undefined>;
    /**
     * AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
     */
    declare public /*out*/ readonly awsAccessKeyId: pulumi.Output<string>;
    /**
     * AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
     */
    declare public /*out*/ readonly awsSecretAccessKey: pulumi.Output<string>;
    /**
     * Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
     */
    declare public readonly budgetPeriod: pulumi.Output<string>;
    /**
     * Epoch seconds the key was minted.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
     */
    declare public /*out*/ readonly enabled: pulumi.Output<boolean>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    declare public readonly issueAwsCredential: pulumi.Output<boolean | undefined>;
    /**
     * Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
     */
    declare public readonly maxBudgetCents: pulumi.Output<number | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    declare public readonly rpmLimit: pulumi.Output<number | undefined>;
    /**
     * The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
     */
    declare public /*out*/ readonly secret: pulumi.Output<string>;
    /**
     * Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    declare public readonly tpmLimit: pulumi.Output<number | undefined>;

    /**
     * Create a VirtualKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: VirtualKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VirtualKeyArgs | VirtualKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VirtualKeyState | undefined;
            resourceInputs["allowedPools"] = state?.allowedPools;
            resourceInputs["awsAccessKeyId"] = state?.awsAccessKeyId;
            resourceInputs["awsSecretAccessKey"] = state?.awsSecretAccessKey;
            resourceInputs["budgetPeriod"] = state?.budgetPeriod;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["issueAwsCredential"] = state?.issueAwsCredential;
            resourceInputs["maxBudgetCents"] = state?.maxBudgetCents;
            resourceInputs["name"] = state?.name;
            resourceInputs["rpmLimit"] = state?.rpmLimit;
            resourceInputs["secret"] = state?.secret;
            resourceInputs["tpmLimit"] = state?.tpmLimit;
        } else {
            const args = argsOrState as VirtualKeyArgs | undefined;
            resourceInputs["allowedPools"] = args?.allowedPools;
            resourceInputs["budgetPeriod"] = args?.budgetPeriod;
            resourceInputs["issueAwsCredential"] = args?.issueAwsCredential;
            resourceInputs["maxBudgetCents"] = args?.maxBudgetCents;
            resourceInputs["name"] = args?.name;
            resourceInputs["rpmLimit"] = args?.rpmLimit;
            resourceInputs["tpmLimit"] = args?.tpmLimit;
            resourceInputs["awsAccessKeyId"] = undefined /*out*/;
            resourceInputs["awsSecretAccessKey"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["secret"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["awsSecretAccessKey", "secret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(VirtualKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VirtualKey resources.
 */
export interface VirtualKeyState {
    /**
     * Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
     */
    allowedPools?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * AWS-style access key id, when issueAwsCredential is true. Returned only at creation.
     */
    awsAccessKeyId?: pulumi.Input<string | undefined>;
    /**
     * AWS-style secret access key, when issueAwsCredential is true. Returned only at creation; stored in state and never re-read.
     */
    awsSecretAccessKey?: pulumi.Input<string | undefined>;
    /**
     * Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
     */
    budgetPeriod?: pulumi.Input<string | undefined>;
    /**
     * Epoch seconds the key was minted.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Whether the key currently resolves. A key is created enabled; disable it out-of-band via the admin API.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    issueAwsCredential?: pulumi.Input<boolean | undefined>;
    /**
     * Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
     */
    maxBudgetCents?: pulumi.Input<number | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    rpmLimit?: pulumi.Input<number | undefined>;
    /**
     * The plaintext bearer secret (sk-bb-...). Returned only at creation; stored in state and never re-read.
     */
    secret?: pulumi.Input<string | undefined>;
    /**
     * Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    tpmLimit?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a VirtualKey resource.
 */
export interface VirtualKeyArgs {
    /**
     * Pools this key may target. Empty/unset means unrestricted. Immutable; changing it replaces the key (the mint spec is fixed at creation).
     */
    allowedPools?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Budget window: one of total, daily, monthly. Defaults to total. Immutable; changing it replaces the key.
     */
    budgetPeriod?: pulumi.Input<string | undefined>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    issueAwsCredential?: pulumi.Input<boolean | undefined>;
    /**
     * Spend cap in cents over the budget window (>= 0). Omit for unlimited. Mutable via PATCH.
     */
    maxBudgetCents?: pulumi.Input<number | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Requests-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    rpmLimit?: pulumi.Input<number | undefined>;
    /**
     * Tokens-per-minute cap (>= 1). Omit for unlimited. Mutable via PATCH.
     */
    tpmLimit?: pulumi.Input<number | undefined>;
}
