// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A governance virtual key (busbar >= 1.5.0): a mintable, revocable, EXPIRING signed-token credential, optionally bound to a `groups:` bucket that carries all budget and rate enforcement (POST/GET/PATCH/DELETE /api/v1/admin/keys). The signed token is returned by busbar only once, at creation, and is stored in state as a sensitive value; refreshes update metadata (group/enabled/state) but never the token. Requires governance to be enabled on the gateway.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as busbar from "@getbusbar/pulumi-busbar";
 *
 * // Mint a governance virtual key (busbar >= 1.5.0): a signed, expiring token,
 * // bound to a `groups:` bucket that carries all budget/rate enforcement, scoped
 * // to the "smart" pool. The signed token is returned only once, at creation, and
 * // stored in state as a sensitive value.
 * const app = new busbar.VirtualKey("app", {
 *     name: "checkout-service",
 *     group: "team-checkout",
 *     allowedPools: ["smart"],
 *     expiresIn: "30d",
 *     labels: {
 *         service: "checkout",
 *     },
 * });
 * export const appKeyToken = app.token;
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Virtual keys are imported by their server-assigned id (the signed token
 * cannot be recovered — it is create-only — and stays null after import).
 *
 * ```sh
 * $ pulumi import busbar:index/virtualKey:VirtualKey app vk_0123456789abcdef
 * ```
 */
export class VirtualKey extends pulumi.CustomResource {
    /**
     * Get an existing VirtualKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VirtualKeyState, opts?: pulumi.CustomResourceOptions): VirtualKey {
        return new VirtualKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'busbar:index/virtualKey:VirtualKey';

    /**
     * Returns true if the given object is an instance of VirtualKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VirtualKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VirtualKey.__pulumiType;
    }

    /**
     * Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
     */
    declare public readonly allowedPools: pulumi.Output<string[] | undefined>;
    /**
     * AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
     */
    declare public /*out*/ readonly awsAccessKeyId: pulumi.Output<string>;
    /**
     * AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
     */
    declare public /*out*/ readonly awsSecretAccessKey: pulumi.Output<string>;
    /**
     * Epoch seconds the key was minted.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
     */
    declare public readonly expiresAt: pulumi.Output<number>;
    /**
     * Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
     */
    declare public readonly expiresIn: pulumi.Output<string | undefined>;
    /**
     * The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
     */
    declare public readonly group: pulumi.Output<string | undefined>;
    /**
     * Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
     */
    declare public /*out*/ readonly groupProvisioned: pulumi.Output<boolean>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    declare public readonly issueAwsCredential: pulumi.Output<boolean | undefined>;
    /**
     * Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
     */
    declare public readonly parent: pulumi.Output<string | undefined>;
    /**
     * Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
     */
    declare public /*out*/ readonly token: pulumi.Output<string>;

    /**
     * Create a VirtualKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: VirtualKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VirtualKeyArgs | VirtualKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VirtualKeyState | undefined;
            resourceInputs["allowedPools"] = state?.allowedPools;
            resourceInputs["awsAccessKeyId"] = state?.awsAccessKeyId;
            resourceInputs["awsSecretAccessKey"] = state?.awsSecretAccessKey;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["expiresIn"] = state?.expiresIn;
            resourceInputs["group"] = state?.group;
            resourceInputs["groupProvisioned"] = state?.groupProvisioned;
            resourceInputs["issueAwsCredential"] = state?.issueAwsCredential;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["parent"] = state?.parent;
            resourceInputs["state"] = state?.state;
            resourceInputs["token"] = state?.token;
        } else {
            const args = argsOrState as VirtualKeyArgs | undefined;
            resourceInputs["allowedPools"] = args?.allowedPools;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["expiresAt"] = args?.expiresAt;
            resourceInputs["expiresIn"] = args?.expiresIn;
            resourceInputs["group"] = args?.group;
            resourceInputs["issueAwsCredential"] = args?.issueAwsCredential;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["parent"] = args?.parent;
            resourceInputs["awsAccessKeyId"] = undefined /*out*/;
            resourceInputs["awsSecretAccessKey"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["groupProvisioned"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["awsSecretAccessKey", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(VirtualKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VirtualKey resources.
 */
export interface VirtualKeyState {
    /**
     * Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
     */
    allowedPools?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * AWS-style access key id, when issue*aws*credential is true. Returned only at creation.
     */
    awsAccessKeyId?: pulumi.Input<string | undefined>;
    /**
     * AWS-style secret access key, when issue*aws*credential is true. Returned only at creation; stored in state and never re-read.
     */
    awsSecretAccessKey?: pulumi.Input<string | undefined>;
    /**
     * Epoch seconds the key was minted.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
     */
    expiresIn?: pulumi.Input<string | undefined>;
    /**
     * The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
     */
    group?: pulumi.Input<string | undefined>;
    /**
     * Whether the mint auto-provisioned its bound group leaf (self-service). Known only at creation.
     */
    groupProvisioned?: pulumi.Input<boolean | undefined>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    issueAwsCredential?: pulumi.Input<boolean | undefined>;
    /**
     * Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
     */
    parent?: pulumi.Input<string | undefined>;
    /**
     * Lifecycle state derived by the server: active, disabled, revoked, or tombstoned. A tombstoned/revoked key is treated as gone and planned for recreation.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * The busbar-signed bearer token (bbk_...) — the key credential. Returned only at creation; stored in state and never re-read.
     */
    token?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VirtualKey resource.
 */
export interface VirtualKeyArgs {
    /**
     * Pools this key may target. Omitted/null means ALL pools; an explicit empty list means NO pools. Immutable; changing it replaces the key.
     */
    allowedPools?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the key currently resolves. Defaults to true at mint. Mutable via PATCH (false = reversible disable; the key's `state` reads "disabled").
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Token expiry as absolute Unix seconds. May be set at mint (mutually exclusive with `expiresIn`) and is always computed from the mint response. Changing it replaces the key.
     */
    expiresAt?: pulumi.Input<number | undefined>;
    /**
     * Token lifetime as a duration string (e.g. `7d`, `24h`, `30m`, `3600s`); the token's expiry is mint-time + this. Mutually exclusive with `expiresAt`. Omitting both applies the server default TTL. Write-only mint directive; changing it replaces the key.
     */
    expiresIn?: pulumi.Input<string | undefined>;
    /**
     * The `groups:` bucket this key binds to (at most one); all budget/rate enforcement flows through the group. The group must already exist unless `parent` is set (auto-provision). Omit for an authed-but-unlimited key. Mutable via PATCH: changing it rebinds, removing it unbinds.
     */
    group?: pulumi.Input<string | undefined>;
    /**
     * When true, also mint an AWS-style access-key-id + secret access key (SigV4/Bedrock inbound auth). Both are returned only at creation. Immutable.
     */
    issueAwsCredential?: pulumi.Input<boolean | undefined>;
    /**
     * Mint-time labels echoed onto this key's metric series (Prometheus-safe names; never interpreted by enforcement). Immutable; changing them replaces the key.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Human-readable label (<= 256 chars). Immutable; changing it replaces the key.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Auto-provision target: the EXISTING parent group under which `group` is created as a leaf when it does not yet exist. Write-only mint directive (never echoed by reads). Changing it replaces the key.
     */
    parent?: pulumi.Input<string | undefined>;
}
